### ISSUE TITLE
Feature Request: Multiple devices

### ISSUE THREAD

**Issue by clarakwan** [sylvek/itracing2#1]
Can you add the ability to manage multiple bluetooth devices/keyrings?

**Comment by AlessandroBerta** [comment]
Agreed with request.  The only app that works with my tag...  Need multiple and personalization of parameters (distance)  and more

**Comment by niveka** [comment]
I agree with Clarakwan (the person who commented right before me)

**Comment by sylvek** [comment]
Understood but this feature need to rewrite a big part of my app. So that should take much time.

**Comment by sylvek** [comment]
I have just buy a another itag from eBay thanks to your donation.. \o 
I could code multi support soon..

**Comment by xila76** [comment]
+1 for me, I need this feature too

**Comment by sylvek** [comment]
well .. good news! I have a fresh version with multi-devices support and i need testers :)
feel free to test it! https://play.google.com/apps/testing/net.sylvek.itracing2

**Comment by sylvek** [comment]
I added a long click on the device list and to rename them, but I think it will not be enough

**Comment by sylvek** [comment]
Done!
