### ISSUE TITLE
"something goes wrong" error message

### ISSUE THREAD

**Issue by javierfurus** [sylvek/itracing2#104]
This is the error message I recieve when I uncheck/check iTag beep in the preferences tab. What might be wrong?

**Comment by sylvek** [comment]
What is your itag model? It seems that not all itag brand offer this
feature.

Le dim. 9 avr. 2017 à 18:11, javierfurus <notifications@github.com> a
écrit :

**Comment by javierfurus** [comment]
How can I check that?

**Comment by sylvek** [comment]
you could check the traces => https://github.com/sylvek/itracing2/wiki/Contribuate-by-reading-traces

and confirm me if you have an UUID (or not) => 00001803-0000-1000-8000-00805f9b34fb

if you are not familiar with the android sdk, you could discover it by using a bluetooth app' tool like:
https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrftoolbox&hl=fr

**Comment by sylvek** [comment]
if you are familiar with java code => https://github.com/sylvek/itracing2/blob/master/app/src/main/java/net/sylvek/itracing2/BluetoothLEService.java#L335

**Comment by sylvek** [comment]
yes thks!
please, confirm me that you don't have a service with UUID => 0x1803

**Comment by javierfurus** [comment]
No, I don't have one with that uuid

**Comment by sylvek** [comment]
:-/ so .. you can not disable this feature. It is hard coded on your iTag :(
(it is why some iTag are less expensive, i guess)

**Comment by javierfurus** [comment]
doesn' t the 0x00 No Alert help? If not thank thank you very much for your great work :)

**Comment by sylvek** [comment]
It should be, only if you have the 0x1803 uuid service on your itag..

**Comment by javierfurus** [comment]
I see, unfortunately, I have only 0x1802
