### ISSUE TITLE
How to turn off itag ringing after outofrange

### ISSUE THREAD

**Issue by znaczki654** [sylvek/itracing2#105]
I have a problem due to that if I would like to use that iTag, if my keys with that are too far that it's ringing and nothing helps, what to do?

**Comment by znaczki654** [comment]
And also "something went wrong" I was reading other posts about that but I can't understand them.

**Comment by sylvek** [comment]
hi,

the nominal behavior is what you are describing.
when the link between phone & itag is lost.. the itag is ringing.

some iTag are a weak "copy" without all options available on the "original" iTag.
in some iTag, the ringing (when the link is lost) is "hard coded" on the iTag.

And the new option that i added recently can not work properly (it is why you see "something went wrong")
