### ISSUE TITLE
Two single clicks on different Tags is marked as a double click

### ISSUE THREAD

**Issue by thejeshgn** [sylvek/itracing2#107]
**Flow:**

 Tag1 - Single Click
and then quickly (within 300MS)
Tag2 - Single Click

The App considers it as Double Click on Tag2.

**Solution:**

On line https://github.com/sylvek/itracing2/blob/master/app/src/main/java/net/sylvek/itracing2/BluetoothLEService.java#L186

Along with comparing time and UUID, we also need to compare the device address or name to the last clicked device address or name. 

**Pseudo code**

```
public void onCharacteristicChanged(BluetoothGatt gatt, BluetoothGattCharacteristic characteristic) {

tagAddress = gatt.getDevice().getAddress();
or
tagName = gatt.getDevice().getAddress();

//compare the present Address to the last device Address

if (lastChange + delayDoubleClick > now &&  && characteristic.getUuid().equals(lastUuid) &&  tagAddress.equals(lastTagAddress)) {

```
@sylvek 

What do you think?
If you think it makes sense then I can make changes and send you a pull request.

Other:
Ref: https://github.com/sylvek/itracing2/issues/81

**Comment by sylvek** [comment]
You are clearly right.. i don't know why i've compared the characteristic uuid oO
feel free to make a pull request 👍

**Comment by thejeshgn** [comment]
Sent.

**Comment by sylvek** [comment]
Fixed
