### ISSUE TITLE
Adding external intent for "immediate alert"

### ISSUE THREAD

**Issue by m-jurczyszyn** [sylvek/itracing2#111]
So far I couldn't find a way to "ring the Tag" using Tasker - Intent.
Since I don't know how to code this feature myself, I make this feature request.

Please add intent for "immediate alert". (to be available in AndroidManifest.xml)
Device selection suggestions: -name, -MAC address.

**Comment by sylvek** [comment]
i'm agree with you..

**Comment by sylvek** [comment]
https://github.com/sylvek/itracing2/pull/113

**Comment by sylvek** [comment]
@m-jurczyszyn try the beta version (from the google play store)

**Comment by m-jurczyszyn** [comment]
I installed the beta version.
Immediate alert intent failed with numerous attempts.
My data field value in Tasker: `itag://FF:FF:B0:01:7D:76`
Can someone confirm that this works?

**Comment by sylvek** [comment]
Ok thanks, do you have stack trace? I will check it tonight. Regards

Le mar. 27 juin 2017 à 19:06, m-jurczyszyn <notifications@github.com> a
écrit :

**Comment by m-jurczyszyn** [comment]
Sorry for late reply.
[log.txt](https://github.com/sylvek/itracing2/files/1110364/log.txt)

Hope this helps.

**Comment by sylvek** [comment]
you should send an Intent with action: `net.sylvek.itracing2.action.IMMEDIATE_ALERT`

and data have to contain :
```
        // itag://mac_address
        final Uri data = intent.getData();
```
