### ISSUE TITLE
[feature request] ST17H26 support

### ISSUE THREAD

**Issue by mariarti** [sylvek/itracing2#112]
Thanks for great app, it works with iTag:
model on pcb
RB-FD01Ver1.6
20160303

on chip
ST17H26
CH1641
CH7415.1

![bluetooth_face](https://user-images.githubusercontent.com/1933140/27518482-4e32aea2-59e1-11e7-8048-7297f727db4f.jpg)
![rb-fd01](https://user-images.githubusercontent.com/1933140/27518503-d1da708c-59e1-11e7-84aa-9204a3161835.jpg)
datasheet http://www.docin.com/p-1814309628.html (ver.1.5.0 2015/10/26)

but it has some troubles with switching off iTag on out of range function (like here https://github.com/sylvek/itracing2/issues/105), maybe datasheet can help to improve (may be not due to firmware)

and finally - would be very very useful to add beacon counter or similar near level due to one most important reason: If I've lost my cat, I went to search for iTag, and level of signal can be so poor, that it might not be catchable but  beacons could be still available (recognizable) by MAC address. That can help understand that I've get to the detecting zone instead of waiting other data like now that appears in good signal area with sufficient packets of data from air. Or maybe put this on switchable checkbox in settings with "Show debug info" title.
May be also exist other useful functions or parameters that could help figure out that you get to zone of iTag.

upd
datasheet from 2016/7/7 Ver. 2.0.0 http://www.docin.com/p-1814297477.html 
for ST17H26, ST17H28, ST17H29, ST17H30, ST17H38

**Comment by sylvek** [comment]
thank you for your datasheet!
your feature to improve detection is a smart idea.. time is messing :-/

**Comment by mariarti** [comment]
Small edition: it would be more convenient with counting  beacons add sound like "beep".
Once I went to find my pet, and unexpectedly rain start and i should still look to screen which covers by water of rain.

**Comment by TBSliver** [comment]
For future searchers looking for the datasheet from a non-pay to get page, here is the manufacturers site for ST17H26: http://lenzetech.com/techSpecs/

**Comment by ExcViral** [comment]
How can I program this mcu?

**Comment by wsuchy** [comment]
@excviral It seems to be an OTP memory. Even if you had an unprogrammed chip you would still need to use dedicated programmer IMO.
http://lenzetech.com/specifST17H26/

**Comment by BoKKeR** [comment]
What is exactly keeping us from having the ST17H26 work with the App?

**Comment by mohammadrezaradpour** [comment]
Hi. 
how programming/debugging/testing ST17H29?

**Comment by mohammadrezaradpour** [comment]
Hi. 
how programming/debugging/testing ST17H29?

**Comment by mohammadrezaradpour** [comment]
Hi. 
how programming/debugging/testing ST17H29?
