### ISSUE TITLE
[feature request] show distance 

### ISSUE THREAD

**Issue by msoftware** [sylvek/itracing2#114]
Hi,

is there a possibility to show the distance (signal strength) so I can check, if I move into the right direction?
I would be very happy to receive your positive feedback 

Regards
Michael

**Comment by sylvek** [comment]
Hi @msoftware
i've done some tests but calculate a distance is too approximative.
imagine, if you have your Tag in a pocket the signal is significantly decreased.
display a color (red, yellow or green) is what i found as best for this feature (it's the color inside the circle)
