### ISSUE TITLE
High battery drain

### ISSUE THREAD

**Issue by tecufanujacu** [sylvek/itracing2#115]
When using this app I have an high battery drain caused by OS, what can I do to reduce it?

**Comment by sylvek** [comment]
Hello, what is the model of your phone and the version of your OS?
I simple way could be to uncheck your itag on the devices list. By doing
that you remove the permanent link between your phone and your itag.

Regards
Sylvain

Le sam. 22 juil. 2017 à 11:22, tecufanujacu <notifications@github.com> a
écrit :

**Comment by tecufanujacu** [comment]
I have an LG G2 D802 whith CyanogenMod 13 and Lambda Kernel.
Using itracing2 I have an high battery drain caused by Android OS and precisely there is bluedroid_timer that causes really a lot of wakelocks.

Concretely the battery normally last to me almost two days, when I use itracing2 the battery lasts an half day.

Obviously I have already dismissed using the itag but I'd like to know if there is something that I can do to use it and reduce the battery drain.

**Comment by sylvek** [comment]
woot 2 years later :-x
you should upgrade your distrib.. i do nothing special and i suppose that the problem occurs on the internal stack of the os.
