### ISSUE TITLE
Import to Android Studio 2.3.3

### ISSUE THREAD

**Issue by BluePackStack** [sylvek/itracing2#117]
As stated in https://stackoverflow.com/questions/25348339/how-to-import-an-existing-project-from-github-into-android-studio

I should be able to just import the unzipped git download content into Android Studio.
but there I just get: Cannot import anything from C:/Users/...

What do I have to do instead(i am very new to android software)? :(

I tried to unzip and import as well, but the  config .xml files in .idea directory is missing and so it won't compile. :(

probably i am missing something very easy, but i don't know what to do now. :(

**Comment by sylvek** [comment]
Hey :)
i guess you can get source by a 
```
git clone https://github.com/sylvek/itracing2.git
``` 
after that, you could "import" the project (from your local copy) from your Android Studio (i use IntelliJ with Android plugin)
