### ISSUE TITLE
OutofRange Behaviour

### ISSUE THREAD

**Issue by BluePackStack** [sylvek/itracing2#118]
First off all! Amazing App! 

Phone: Andorid 4.4.2  Itag: NoName

**After connecion loss**, key and mobile start ringing.

To stop ringing. Turn it off via pressing the button(optional) and checking the appearing option on the phone, which works all right for me.

Then in **foreground modus**:
reconnecting only possible by restarting the app with the task manager **or** deactivating foreground modus and then restarting the app by wiping it away from desktop an restarting.

In **normal modus**:
 wiping the app from desktop and restarting will work(prefer this)

Am I missing something here? It's hard to find out what the app should act like in normal, since I couldn't find a short doc or so.

**Comment by sylvek** [comment]
hi,

first of all, sorry for the delay.
It depends on your iTag model and you phone.
Bluetooth LE stack is not really well implemented on several phones and devices, and it's a shame :(
On my own Galaxy S6 Edge and Itag (expected as original) the iTag is reconnected natively.
With no-named iTag, it powers off itself if OutOfRanged and you have to restart everything.

I don't have any time to support iTracing2 for now … ;(
