### ISSUE TITLE
Error in Toggling Proximity Alarm 

### ISSUE THREAD

**Issue by johnmfoxjr** [sylvek/itracing2#119]
ERROR 1
Receiving "Something Goes Wrong" notification bubble when toggling the proximity selector/checkbox.

ERROR 2
Command to "beep when bluetooth connection is lost" is sent to devices, regardless of the state of the proximity selector/checkbox.

RESOURCES 
https://www.dropbox.com/s/lt6v9krmx4rd1ce/Screenshot_20171102-074503.png?dl=0
https://www.dropbox.com/s/3o02hazu3dob908/Screenshot_20171102-074516.png?dl=0
https://www.dropbox.com/s/5z41tjx5tky3li2/Screenshot_20171102-074525.png?dl=0

**Comment by sunsero** [comment]
Error 2 is a real problem because it doesn't even help to turn off the beep with other tools - iTracing2 will turn it on again.

**Comment by sunsero** [comment]
I did some research and it seems ERROR 1 is most probably occurring if the device does not expose a LINK_LOSS_SERVICE. This is not fixable by iTracing2 then but the error message should be more detailed.

I therefore don't think anymore that the app turns on the setting for beeping of the device when it gets disconnected like ERROR 2 describes. It's IMHO just not possible to do this when the device does not offer LINK_LOSS_SERVICE.

**Comment by sylvek** [comment]
i'm agree with you @sunsero. Some devices are cheap enough to not offer a suitable implementation. also, i discovered that some devices hardcoded the "link lose connection beeping".
