### ISSUE TITLE
Intents for tasker and multiple BLE devices

### ISSUE THREAD

**Issue by DaLanik** [sylvek/itracing2#120]
Hello, thanx for the great an unique program, the only one which does something useful with BLE tags :)

Anyways, questions :)

* What are all the possible intents I can send to Tasker for various events? I know net.sylvek.itracing2.itag1.button is click, and net.sylvek.itracing2.itag1.doubleclick is double click. What about onconnect, out of range?

* How do I adress other devices? I see that my tag is "itag1" from the intent, I suppose second tag would be itag2? But what decides which device is which number?

Thanx!

**Comment by stolarek** [comment]
Hello everybody, I need a better description too. Important for me is how to send codes to my app.
Thanks
Damian

**Comment by sunsero** [comment]
I think you can completely free specify intents that will be sent to the system and be possibly received by Tasker.

Please note that version 2.4.2 like on Play Store does NOT work with Tasker. Version 2.4.1 released on github does.

**Comment by sylvek** [comment]
hoo @sunsero interesting! .. i will check the difference between those 2 versions.

**Comment by sylvek** [comment]
frankly .. it should work on 2.4.2 and after.

**Comment by sunsero** [comment]
I'm sure it's been like that. Tasker itself often has to struggle with issues like that when changing the target API of the APK.

**Comment by sylvek** [comment]
i found that... https://github.com/domenpk/itracing2/commit/f3f7596c43a7eb9e328adab725691b1e9892f346

**Comment by sylvek** [comment]
ok... https://developer.android.com/guide/components/broadcasts.
So that's right, between 2.4.1 and 2.4.2 i broke the compatibility.
But after the version 2.5.2, i did a fix 🤔 
https://github.com/sylvek/itracing2/commit/ccee0426ee84eb1abd0b2c72870d46e080449bb3

**Comment by sylvek** [comment]
actions are sent that way: https://github.com/sylvek/itracing2/blob/bc82601920763b4253575fa638840c91f053cd55/app/src/main/java/net/sylvek/itracing2/BluetoothLEService.java#L226

**Comment by sylvek** [comment]
so, i'll try by myself with a trial version of Tasker, but having a look of the `sendAction` function.

```
        private void sendAction(Preferences.Source source, String action) {
            final Intent intent = new Intent(BROADCAST_INTENT_ACTION.equals(action) ? ACTION_PREFIX + action + "." + source : ACTION_PREFIX + action);
            intent.putExtra(Devices.ADDRESS, address);
            intent.putExtra(Devices.SOURCE, source.name());
            sendBroadcast(intent);
            Events.insert(getApplicationContext(), source.name(), address, action);
            Log.d(TAG, "onCharacteristicChanged() address: " + address + " - sendBroadcast action: " + intent.getAction());
        }
```

Actions are https://github.com/sylvek/itracing2/blob/bc82601920763b4253575fa638840c91f053cd55/app/src/main/java/net/sylvek/itracing2/Preferences.java#L18

So the fullname is like that when custom event is set : net.sylvek.itracing2.action.BROADCAST_INTENT.single_click
With 2 extras .. the device address and the source name

device address is "mac" address from the device (i guess) and i don't really know why I set the source a second time 🤔

**Comment by sylvek** [comment]
i found an another source more accurate. https://github.com/sylvek/itracing2/wiki/Broadcasted-Actions

i don't remember what `BROADCAST_INTENT` is for.

**Comment by sylvek** [comment]
https://github.com/sylvek/itracing2/wiki/Tasker
