### ISSUE TITLE
Showing distance (in meter)

### ISSUE THREAD

**Issue by klorinczi** [sylvek/itracing2#121]
Could be possible to show on dashboard, how far away is the itag?
I would need the distance in meter.

**Comment by sylvek** [comment]
hey @klorinczi problem is .. there is no way to match a signal strength with a distance.
It depends on the environment, the quality of the antenna, the power, etc..
One measure is missing : how db the iTag is able to have for a given meter (like 1 meter).
FYI: This measure is sent by the "iBeacon" that use the same technology.

**Comment by pirulo6666666** [comment]
but it would be possible to put the signal strngth in a range of 0 to 100 in a status bar.

**Comment by sylvek** [comment]
not really.. because we have db unit i guess.. and it's difficult (as meter) to transform it to percent for the same reason. How many db of the signal your phone is able to receive? it depends on your phone.. the environment, etc.

**Comment by pirulo6666666** [comment]
so in db to have an idea of if I approach or I go away when I'm looking for it.

**Comment by sylvek** [comment]
more the value is high more you are close to your device.
