### ISSUE TITLE
iTAG Phone Unlock via Android "Smart Lock"

### ISSUE THREAD

**Issue by LuckyLuzz** [sylvek/itracing2#123]
Hello,
I am very glad I found this respithory. Good work with the App :)

I bought two iTAG in China, I wanted them to unlock my Phone over Security App "Smart Lock"  while in range, so I thought. But I just found out that the divices dosn't connect the the my Samsung S5 without a App. It allway asks for a Pin, which is not 0000 or 1234 or so.... 

So my question is: Is there a way to connect the ITag to my Phone without a App so I could use it as "Secure Device"  same as my Bluetooth Speaker?

![Uploading IMG_20171209_172630.jpg…]()
![img_20171209_172641](https://user-images.githubusercontent.com/20560944/33797614-8ea49204-dd0b-11e7-9813-8c16f4699961.jpg)

**Comment by LuckyLuzz** [comment]
so there is no way to connect a iTag without a App?

**Comment by sylvek** [comment]
With bluetooth LE/4 (and more), you have to use a dedicated app to interact with your device.
Bluetooth 4 (and more) works with "profils" and iTag device implements "find me" profil. (https://en.wikipedia.org/wiki/Bluetooth_Low_Energy)

If Android OS implements this profil, it should work. Instead, you have to use a compatible app, like iTracing2.
