### ISSUE TITLE
iTag beep

### ISSUE THREAD

**Issue by neresus** [sylvek/itracing2#124]
By unchecking iTag beep (beep out of range) if shows text: somethings strange happens

Itag beeps anyway when I go to another room.. I am doing something wrong?
All itags haves this functionality? Or cheap ones from china does't..
I have something like this:
https://www.aliexpress.com/item/1pc-Anti-lost-alarm-Smart-Tag-Wireless-Bluetooth-Tracker-Child-Bag-Wallet-Key-Finder-GPS-Locator/32791727548.html?spm=a2g0s.13010208.99999999.285.tTHtmi

**Comment by rubeycubey** [comment]
Yes, I have the same issue.  I would like to be able to set the iTag to not beep when my phone is out of range.

BTW: thank you:
1) for publishing an open source app (they are inherently more trustworthy)
2) not requiring crazy permissions.

**Comment by rubeycubey** [comment]
If I connect to the device with nRF Connect it shows only one writable service is "Immediate Alert".  If there are no other writable services, does this mean this particular device does not provide a controllable setting for beeping when it loses connection or goes out of range?

**Comment by sunsero** [comment]
Immediate Alert is the right setting but iTracing2 will erroneously turn the beep on again.
