### ISSUE TITLE
Itag gps maps itracing 2

### ISSUE THREAD

**Issue by break69** [sylvek/itracing2#125]
Bonjour, 
Pouvez vous créer un onglet avec la carte de maps pour localiser nos itag ?

Ou est ma voiture.
Ou est mon chien, chat.

I dont speak english but in 2 words
Can you creat a tab for locate my itag whit maps.
Thanks for your job.
I love this app is the better 
Sorry for my english.

**Comment by sylvek** [comment]
Bonsoir,

Étant français, ça va aider 😉
Pour moi cette carte existe déjà.
Si on sélectionne une action (click, double click..) avec  capture current
location.. Alors nous pouvons avoir une trace dans l'historique qui, si on
clique dessus, affichera une carte.
Le problème est que je n'ai plus le temps nécessaire pour faire évoluer mon
application ☹️

Cdt
Sylvain

**Comment by break69** [comment]
Merci de votre réponse.
J'avais bien prit connaissance de cette manipulation qui dépanne bien.

J'en suis attristé car je trouve aucune autre application remplissant bien le rôle que je souhaite sauf la votre.

j’espère que le temps vous permettra d'enrichir cette-ci et si cela arrive veuillez me le stipuler alors je serais prêts à vous faire un petit don.

Petite question annexe:
Combien de temps vous à il fallu approximativement pour créer cette application ?
