### ISSUE TITLE
Out of range

### ISSUE THREAD

**Issue by or2122** [sylvek/itracing2#126]
I walk to the other end of the hallway and nothing is beeping or alarming. I set it to ring the phone and vibrate and detect location. So you need to be really far away? I loved this feature in the original app.

**Comment by sylvek** [comment]
Hi,

It should work but the range depends on several parameters.. your phone,
the battery level of your iTag.. obviously if you're in a cleared ground,
the range will be better :)

**Comment by klorinczi** [comment]
Unfortunately my iTAG always do false reports, loses connection. Connects, but often show out of range error, even when having near the phone.
