### ISSUE TITLE
Incrementing button click 

### ISSUE THREAD

**Issue by ugurcanatas** [sylvek/itracing2#128]
Hey there ! I was looking at the suggestion about single/double click. I wonder if i can implement triple or quadruple click somehow.Maybe tuning the 300 ms delay. Do you guys have any ideas about this ? 

Have a nice day everyone !

**Comment by sylvek** [comment]
ofcourse!

**Comment by ugurcanatas** [comment]
Thanks ! I am going to try to make this happen. In the meantime , if you have any suggestions about how to implement this let me know. I could use some help . I will update this post when i make any progress.

Have a nice day !

**Comment by sylvek** [comment]
done :)
