### ISSUE TITLE
Adding trust zone

### ISSUE THREAD

**Issue by lyriss113** [sylvek/itracing2#129]
The app is by far the most useful for Itags. There just one thing that could make the app better. 

Stop the app when you enter  a trusted zone like home or work ( using home wifi or/and geofance) and start it when once you get out the trusted zone.

Thanks.

**Comment by lyriss113** [comment]
Thanks Sylvain for the time you took to answer.
the thing is without that feature the app becomes annoying at home or work. that's so sad because your app is the most useful one.

The only solution left is to use other app to play that role ( Like MacroAndroid ), but until now i don't know how to use the Custom action feature ( using intents )

if i know how to creat notifications of the status ( disconnected, connected ) i can use Macrodroid to take action based on that.

do you have any idea how to make that possible ( and easy for a beginner ) ?

Thanks.

**Comment by sylvek** [comment]
hi @lyriss113 and sorry for the delay :(
sadly i'm not a user of Tasker or any other app' to customize things.
so if someone else can help you 🙏
