### ISSUE TITLE
Gradle bulding

### ISSUE THREAD

**Issue by testsw110** [sylvek/itracing2#130]
Dear Sylvek

Thank you for sharing this App.
I've downloaded it and open with Android Std, but cannot done the gradle sync progress 
Could you please guide me. this is an  error which Android Std show me.

Error:(50, 24) Failed to resolve: tools.fastlane:screengrab:1.0.2
<a href="openFile:C:/Users/MyPC/AndroidStudioProjects/itracing2-master/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Thank you
Josef

**Comment by sylvek** [comment]
Gradle was updated, please try again.
