### ISSUE TITLE
Add bluetooth headset as lost tracker? 

### ISSUE THREAD

**Issue by klorinczi** [sylvek/itracing2#131]
Could be possible to add bluetooth headset as a lost tracker?

**Comment by sylvek** [comment]
It seems not possible because of bluetooth profile not compatible with headphone

**Comment by klorinczi** [comment]
Well, until a bluetooth headset is connected, it means the phone is within 5-10 meters.

When the bluetooth headset is disconnected, it means, the phone is out of the range, so can trigger the app to start the alarm.

This can work, just support have to be implemented into the app.
