### ISSUE TITLE
[Feature Request] Add alarm volume setting, increasing volume

### ISSUE THREAD

**Issue by klorinczi** [sylvek/itracing2#132]
Feature Requests:
- alarm volume setting for each place, where sound can be chosen, 
- option to use increasing volume,
- option for time, how long should reach the maximum volume (should default to 30 second) .

BUG:
Currently the volume setting is set to maximum. 
There is also a bug:
- the maximum volume is kept, when alarm is finished. The volume level used previously should be restored after alarm is finished.

**Comment by sylvek** [comment]
good idea, but i can apply only a minimal support :(
