### ISSUE TITLE
how set manually distance for state out of rang devices?

### ISSUE THREAD

**Issue by nastarandm** [sylvek/itracing2#135]
Is it possible we define manually distance for out of rang?
Because I want to set a maximum distance on some devices to alert

**Comment by sylvek** [comment]
hello we can not :(
your smartphone doesn't know the distance.. it only knows if iTag is connected or not.

**Comment by sylvek** [comment]
It depends on your phone.. your itag.. And your home (walls, etc). With my
own experience, 10 meters are more realistic.

**Comment by nastarandm** [comment]
thanks for answering and your experience. So the mode out of range is the same as the disconnect state? and we can't set state for more than 10m?

**Comment by sylvek** [comment]
out of range and disconnected state are managed directly by the OS.
iTracing recieves events (disconnected, out of range, and so on) and can
not deal with this kind of parameters (especially with iTag chinese clone).
Sorry :-/
