### ISSUE TITLE
APK? Beta not availabe on Play Store

### ISSUE THREAD

**Issue by andreapx** [sylvek/itracing2#136]
Hi,
is it possibile to get the APK since che beta is not available on the Play Store in my country (Italy).
Thanksn

**Comment by sylvek** [comment]
that's rignt .. i don't know why but itracing2 doesn't respect the new android policy oO

**Comment by andreapx** [comment]
Could you post the link to the APK?

**Comment by sylvek** [comment]
could you please try this apk?

[app-release-2.4.2.apk.zip](https://github.com/sylvek/itracing2/files/2545228/app-release-2.4.2.apk.zip)

**Comment by andreapx** [comment]
It finds the itag and react at clicks, but I can't use the intent with tasker.
I've followed the manual on [this](https://github.com/sylvek/itracing2/issues/2#issuecomment-167861605) post, but tasker doesn't seem to receive the intent (the log is empty).
Am I doing something wrong?

**Comment by sylvek** [comment]
Hum I haven't done changes on my code with this version, I will check but
the problem could come from your side..

**Comment by andreapx** [comment]
Yes yes, I know that most likely is something II'm doing wrong, but I can't figure out what!
Thanks!¡!

**Comment by andreapx** [comment]
My bad, I just found out that I left a space at the beginning of the intent string...
Thanks!
