### ISSUE TITLE
Recommended Devices in Wiki Out-of-Date

### ISSUE THREAD

**Issue by jamesg-nz** [sylvek/itracing2#137]
The URLs to purchase the MLE 15 and Quintic PROXR are out-of-date.

Does anyone have URLs to known good devices without firmware oddities?

i.e. don't power off when link is lost, can also turn on/off beeping when link is lost.

**Comment by sylvek** [comment]
you right! 

but the only real device that works fine is the Quintic PRO XR and it disappeared of internet

so i prefer removing links :-/
