### ISSUE TITLE
Can't detect my ST17H26

### ISSUE THREAD

**Issue by JCAK1967** [sylvek/itracing2#138]
Hi. I'm testing itracing2 but when I search for availables devices the app can't found my itag with chip ST17H26. PCB model RD-FD01Ver1.6

I'm trying using Android Studio (last version) and download de app from Google. Both ways with the same results, not found devices. nRFConnect and LeGatt works fine.

What could be wrong, could some one help me to solve this, please?

Best regards.

**Comment by JCAK1967** [comment]
Hi ... I solve the problem for my self. Opening aplicaciones -> configurations and enable manually the permissions work fine.
Best regards

**Comment by BoKKeR** [comment]
Thanks for this tip. Works for me too!
