### ISSUE TITLE
App requires location service permission to work

### ISSUE THREAD

**Issue by fquirin** [sylvek/itracing2#139]
Maybe helpful to others: Without manually setting the location services permission (Android system app settings) the iTag will not be found (Android 7.0).

[EDIT] ... and phone permission to actually do something ^^

**Comment by domenpk** [comment]
#141 Addresses this (although it doesn't really handle accept/deny, it just asks on start).

**Comment by sylvek** [comment]
Seems fixed on the new version 2.5.3
