### ISSUE TITLE
Add a signal meter

### ISSUE THREAD

**Issue by DaveE128** [sylvek/itracing2#14]
If you could add a signal meter (perhaps with a bar graph) that updates every few seconds, it would be really useful for finding the tag when misplaced. You could tell if you are getting closer or further away when you move by whether the signal gets stronger or weaker. A graphical representation would be good as non-technical people will not understand that a bigger negative number means a weaker signal as they do not understand dB!

**Comment by sylvek** [comment]
good idea.. but maybe a % metric should be better

**Comment by DaveE128** [comment]
For techy people dB is fine, but for others, percentage would be better. However I think a bar chart type indicator gives the best visual feedback. If it can refresh every few seconds it would be good.

**Comment by sylvek** [comment]
I done a first test this morning and rssi jumps just by adding my hand around my phone :( (my itag was only a few centimeters front of me)

**Comment by sylvek** [comment]
instructive… http://blog.bluetooth.com/proximity-and-rssi/

**Comment by sylvek** [comment]
i released a new version with a signal quality in percent.. feel free to use it... but i am disappointed about the quality reception quality of my itag :(
