### ISSUE TITLE
Events History shows buttons presses but actions are not triggered

### ISSUE THREAD

**Issue by teetertime** [sylvek/itracing2#142]
Im using these BLE devices:
https://www.aliexpress.com/item/32933123912.html
(RB-FD02Ver1.9 , 20180606)

In itracing2 they show up as itag devices and connect just fine, however when an event is triggered (single press, double press, out_of_range) although it is logged in the history, no action is actually taken. Any idea why the actions aren't being triggered?

The button press is registered fine in the FindElfi app to trigger the camera.

**Comment by Oleg69** [comment]
Hi,
I have the same problem with this divice: https://www.aliexpress.com/item/32814415280.html
MI 9 [OFFICIAL]Pixel Experience [AOSP[2019/07/15] Android 9
App Version 2.4.2
Any solution/suggestion?
Thank you

**Comment by Oleg69** [comment]
Hi,
I solved this problem by usind the previous version 2.4.1.
Tasker and Intents works great for me yet.
Thanks

**Comment by sylvek** [comment]
Oohh interesting. @Oleg69 could you try with the last version ? 2.5.3
