### ISSUE TITLE
IMMEDIATE ALERT

### ISSUE THREAD

**Issue by Oleg69** [sylvek/itracing2#143]
Any suggestion/help to send intent from Tasker for ALERT?
I tried:
Action field: net.sylvek.itracing2.action.IMMEDIATE_ALERT
Data field: itag
Data field: XX:XX:XX:XX:XX:XX (itag MAC)
Data field: itag://XX:XX:XX:XX:XX:XX

Thanks

**Comment by sunsero** [comment]
Being able to send a beep from Tasker to the iTag would be a very nice feature. However I don't think this feature is implemented as accessible via intents in iTracing2, is it?

**Comment by sylvek** [comment]
Hey 👋with Android 8+ it seems difficult to interact by intent. If someone have information to do that.. Be my man.

**Comment by sylvek** [comment]
by reading my code, it seems possible with the last version 🤔 
https://github.com/sylvek/itracing2/blob/bc82601920763b4253575fa638840c91f053cd55/app/src/main/java/net/sylvek/itracing2/BluetoothLEService.java#L333
