### ISSUE TITLE
calling webservice from custom action

### ISSUE THREAD

**Issue by mrybson** [sylvek/itracing2#144]
Hi, 
thanks for your awesome tool. I would be grateful if you could help me get better understanding of the custom action behavior.
I have already prepared a web service that is hosted on a raspberry and is available from the local IP address (192.168..1.65:45455/api) and I can access it from any device that is connected to LAN network. 
I also set the custom action to call this url in the ITracing2 application. This is however never executed, even though in my Event Log I can see the button was pressed. 
My hope was I could use the webservice to do some automation in my home. Could you explain how this works?

**Comment by mrybson** [comment]
On one of the other topics, you said:

> hi @AVL4GITHUB
> 
> to call an URL in background .. it's pretty simple.
> you just have to enter your url in the custom action.
> 
> ex. http://www.my_personnal_website.com/
> 
> iTracing will call in background => http://www.my_personnal_website.com/?address=the_mac_address_of_your_itag&source=a_source
> 
> with a_source is
> 
> * connected
> * out_of_range
> * double_click
> * single_click

I prepared my endpoint and it now accepts the following url:
http://192.168.1.65:45456/api?address=somevalue&source=somevalue2

but this is still not called from the button click.
Any ideas?

**Comment by sunsero** [comment]
It's probably due to API version 26 of the latest release with missing adoptions. If so, version 2.4.1 from github will work.

**Comment by sylvek** [comment]
Could you please, test with le last version ? 2.5.3
