### ISSUE TITLE
Difference in click options

### ISSUE THREAD

**Issue by dexterdoo** [sylvek/itracing2#149]
What does toggle ring the phone, start ring the phone and stop ring the phone all mean?

**Comment by sylvek** [comment]
hello, the toggle allows you to switch on and off the ring phone.
ex. you click 1 time to start, and after a while, you click 1 time to stop the ring.

**Comment by dexterdoo** [comment]
So then what does start the ring phone and stop the ring phone mean?

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 18, 2020 at 3:44 AM, Sylvain M.<notifications@github.com> wrote:   


Closed #149.

**Comment by sylvek** [comment]
you could prefer to only start ring by 1 click and stop it by double click, for example. It's up to you :)
