### ISSUE TITLE
Fix a few wording issues

### ISSUE THREAD

**Issue by DaveE128** [sylvek/itracing2#15]
"Link background:Loss link between device and keyring" is confusing. Does it mean "Background link monitoring:Monitor for lost signal in the background"? Or does it turn on/off all background monitoring?

"Keyrings's actions" reads better as "Keyring actions"

"Simple/double click button action" reads better as "Single/double button click"

"Select the ringtone referred to action" reads better as "Select the ringtone for actions"

"Out of band action" the meaning I unclear. Perhaps this should read "out of range action"?

"Start/stop ring the keyring" reads better as "Start/stop ringing the keyring"

Thanks ks for creating this app. If it keeps working reliably after a few days testing I plan to donate :)

**Comment by sylvek** [comment]
thks for your translations!
Link background is a feature that allow to monitor all background activities.. without, it is impossible to detect a link loss or interact with the click button on the iTag.

**Comment by DaveE128** [comment]
You're welcome.

So, to clarify with background link turned off, you can still make the keyring beep (this seems to work for me) but all other features are disabled? I think I will use this mode as with background link on, the key fob beeps when out of range, and this annoys my colleagues if I leave my keys in the office and pop outside with my phone!

**Comment by sylvek** [comment]
…or fix your colleagues ;)

**Comment by sylvek** [comment]
fixed on the next release
