### ISSUE TITLE
Supporting SDK24 just needs changing 2 lines of code :)

### ISSUE THREAD

**Issue by aguaviva** [sylvek/itracing2#150]
Hi!

It took me changing 2 lines to support SDK 24.

The first change is to substitute 

`startForegroundService(new Intent(this, BluetoothLEService.class));`

by

`startService(new Intent(this, BluetoothLEService.class));`

And the second chance is to comment out 

`.setChannelId(channelId)`

Thanks for your great software! 👍

**Comment by sylvek** [comment]
Hey @aguaviva !

Thank you for helping 👍 
Sadly i had to do some fixes to be able to publish on Google PlayStore.

With Android > 7 it becomes impossible to interact with bluetooth without foreground service.

> Note: If your app targets API level 26 or higher, the system imposes restrictions on running background services when the app itself isn't in the foreground. In most situations, for example, you shouldn't access location information from the background. Instead, schedule tasks using WorkManager.

I'm going to try a trick, could you test it for me ?

**Comment by aguaviva** [comment]
Sure! :) BTW a great use of your app would be to allow itags make a phonecall, that way old people could use them as a panic button in case they fall down or need help.

**Comment by sylvek** [comment]
it should be great .. but i sure at 90% that it is not possible. 
The best i can do is to display the dialer with a given phone number.

**Comment by aguaviva** [comment]
That is of you use Intent.ACTION_DIAL but if you use Intent.ACTION_CALL it will actually make the call, this one will need the CALL_PHONE permission though.

**Comment by sylvek** [comment]
please check it. https://github.com/sylvek/itracing2/pull/151

**Comment by aguaviva** [comment]
Awesome, thanks for the fix, much appreciated! 

Also, note than with your change you can lower the SDK version to 22. I have your app running on an Android 5.1.1 tablet since yesterday and it works like a charm :)
