### ISSUE TITLE
Add actions for low signal strength

### ISSUE THREAD

**Issue by sunsero** [sylvek/itracing2#152]
If you could specify actions for low signal strength it would be possible to react before the signal gets lost. E.g. it might be possible to let the iTag alert before the phone actually gets out of range.

This would be also useful for iTags that cannot have disabled to beep when getting out of range (let the phone warn you about that before it gets out of range)

**Comment by sylvek** [comment]
hi @sunsero and sorry for the delay..

beeping depends on your device model.. some have bip "hardcoded" on it.. some can be re-programmed.
with the little experience that i have, signal indication is just for "fun".. it's very volatile and difficult to use it.
