### ISSUE TITLE
Question: can you send a text/sms?

### ISSUE THREAD

**Issue by debaeneegon** [sylvek/itracing2#153]
Hey I am trying to find a way to make a itag device send a sms when the button is pressed.
Is there anyway to do this with itracing2?

**Comment by Galaxy-Man** [comment]
Sorted.
Added to manifest and used this code.
    <uses-permission android:name="android.permission.SMSManager" />


Added to Custom Action
if (action.startsWith("alert:")) {
    SmsManager smsManager=SmsManager.getDefault();
    smsManager.sendTextMessage("+44xxxxxxxxxx",null,"Hello World",null,null);

}

**Comment by sylvek** [comment]
@Galaxy-Man great work!
On which version of Android does it work on?

**Comment by Galaxy-Man** [comment]
Tghis is running on OS10 Ill try later this week on OS11, OS12 and OS13

**Comment by Galaxy-Man** [comment]
This was just to show it could be done, however for correctness it should be maded into a Class.
