### ISSUE TITLE
Make app available via F-Droid

### ISSUE THREAD

**Issue by sebastianha** [sylvek/itracing2#154]
Hi,

would you like to make your app available via F-Droid? As it is open source this should be possible.
Unfortunately I am not familiar with the process of getting an app to F-Droid but I would be more than happy to find it there.

Regards, Sebastian

**Comment by sylvek** [comment]
i'll check that ! - thks 👍

**Comment by 9w2xne** [comment]
> i'll check that ! - thks 👍

i check in playstore but app seem missing.. any issue with it?

**Comment by sylvek** [comment]
hey !
my app have been deleted from Play Store because it needs "location permission" and i do not ask to user "nicely".
in another side, to publish on f-droid, i have to remove google play lib used to deal with geolocation :D

**Comment by sylvek** [comment]
Publishing on F-Droid seems pretty freaky 😨 ...
And, i need location permission to use Bluetooth scanning (at least on Android 11, and less).. meaning that, i have to ask grant nicely and respectfuly (like said Google). Sadely, i don't have time to do that and i'm stuck here.

i saw a new permission on Android 12 allowing to pair bluetooth without location permission 🤞

**Comment by sylvek** [comment]
sorry for the delay but it should be available :)
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10278

**Comment by sebastianha** [comment]
Yeah, thank you very much!
