### ISSUE TITLE
Open a simple APP

### ISSUE THREAD

**Issue by sergiotas73** [sylvek/itracing2#155]
Will be possible create the posibilita  to open an APP?. I don't understand the INTENT CODE?. Thank you.

**Comment by sylvek** [comment]
yes it's possible by using INTENT .. you're right, it's not easy to find it :(
maybe you can retrieve it  by going on Settings > Applications and notifications > [select your app] > advanced preferences > you'ill find it at the bottom 

ex. "com.android.launcher3"
