### ISSUE TITLE
Any Trick to Make Sure iTag Gets Automatically Reconnected to iTracing2 When It Is Turned Back On?

### ISSUE THREAD

**Issue by yasurok** [sylvek/itracing2#156]
Is there any trick to make sure the iTag gets automatically reconnected to iTracing2 when it is turned back on after being turned off?

When my iTag is connected to iTracing2, they work together the way I expect them to, which is great. It's such a great app that has almost everything I want, and I could not be happier to have found it. 

When I turn the iTag off, iTracing2 detects the disconnect fine. Now, when I turn the iTag back on, sometimes it gets reconnected to iTracing2 immediately, and sometimes not. In the latter case, usually it never gets reconnected. I have not figured out what causes the different behavior. I made sure iTracing2 was running when the iTag got turned on again. I also observed that the iTag advertizes itself while it did not get reconnected.

When automatic reconnection does not occur, I have found that bringing up iTracing2 and checking off and then on the checkbox for the iTag monitoring has iTracing2 get reconnected with the iTag. 

Actually, this is good enough for my own use. The problem is that I am not the intended user here; it is an elderly person, who is not all that great with gadgets. I do not want her to learn about iTracing2, if that is avoidable. 

The fact checking off and on the checkbox is a solution means it can be done. Ideally, I want her iTag to get reconnected automatically at all times, but if it is hard for some reasons, would you please give us a way to programmatically do it, say, by an intent? 

Just in case you are curious about my intended use case, here it is: I want to use an iTag as a tool to help an elderly person not forget to take her cell phone with her when she goes out. Usually, an iTag is attached to something you do not want to forget to take with you, but here the relation is reversed; it's the phone she does not want to forget to take with her. Her iTag will be attached to her house keys, for example --- something she won't forget to take with her when she goes out. If she gets out of her house without her cell phone, her iTag should beep, and hopefully that'll remind her that she should go back and fetch her cell phone.

I also want her iTag to act as an emergency button to call for an outside help. You might think she could just use her phone, but when it is a real emergency and her body or mind is compromised to a degree, you cannot expect her to be able to handle a smart phone. It needs to be a very simple physical button, and an iTag gives you exactly that.

**Comment by yasurok** [comment]
A little update. I have purchased a few more of those what they claim to be iTags. The newly arrived ones advertize themselves as "iTag"s when seen from the nRF Connect app, whereas the one I have used did as "MLE-15." 

Generally speaking, the new possibly real iTags (or simply better knockoffs) work more reliably than the MLE-15. They reliably reconnects to my smart phone when I run iTracing2 the following way:

- have it run in the foreground mode (that's the default behavior), and
- have it restart by an automation app (Automate) when the boot process is complete.

I am wondering if I am doing it right and if there's any better way. Your feedback will be much appreciated.

Thanks!

**Comment by sylvek** [comment]
hi @yasurok and sorry for the delay..

i'm so sorry to be can to help you :(
i don't use anymore my own app'.

my code seems readable and maybe i could explain it a little bit 🤔

Your process seems correct. It also depends on your phone (that manages BLE chip).

**Comment by sylvek** [comment]
hi @yasurok , when i read my code, a way to "force" reconnection could be by switching off/on the bluetooth chip on your phone and regenerate `STATE_CONNECTED`🤔 

https://github.com/sylvek/itracing2/blob/e68a6b440edad05819f36f91637abe732d80d06e/app/src/main/java/net/sylvek/itracing2/BluetoothLEService.java#L96

**Comment by yasurok** [comment]
Thanks a bunch @sylvek. You're an awesome dev. I really appreciate that you took the trouble to look at your code despite the fact you no longer use your own app, just to answer my question.

I am no longer pursuing the original idea I had (making sure an elderly person can ask for emergency help), but I am thinking of using an iTag for my own use for other purposes, so I will eventually come back to iTracing2 for that. I will give it another go then and try to take advantage of your tip to the fullest. Thanks again!

**Comment by sylvek** [comment]
🙏
