### ISSUE TITLE
Please Have it Emit A Broadcast Intent that Signifies Remaining Battery

### ISSUE THREAD

**Issue by yasurok** [sylvek/itracing2#157]
Hi. Would it be too much to ask you to implement a feature for iTracing2 where it emits a broadcast intent that signifies the remaining battery of the iTag? With that, I would like to show an notification when the battery is getting low in an iTag.

You might say, "It's shown in the app!" Yes, I am well aware of it. However, I am trying to construct, using a combination of a bunch of iTags and the iTracing2 app, a simple emergency alert system where an elderly person can push an iTag's button for outside help in case of her emergency.  The assumption is that she lives alone and a little far from me, so I cannot periodically go to her place and check the battery statuses of iTags on her behalf; she will need to be able to know when an iTag is getting low on battery and replace the battery by herself. For an elderly person and complete technophobe, "Check this iTracing2 app periodically and make sure all iTags have reasonably full batteries" is a bit too much to ask. She needs to get a notification when an iTag is going low on battery.

Thanks!

**Comment by sylvek** [comment]
Hi @yasurok  and sorry for the delay.. 

First of all, those kind of information is not really accurate. It depends massively of the hardware design and generally, chinese devices are too cheap to provide those informations. Also, i don't really maintain iTracing2.. i don't have enough time and i not an user of iTracing2 anymore 😫

I think, you should use AirTag devices 🤔
