### ISSUE TITLE
Ability to customize loss link by location 

### ISSUE THREAD

**Issue by DaveE128** [sylvek/itracing2#16]
I find this behaviour annoying as if I'm not there to hear the beeping, it only annoys other people (wife, colleagues) if I leave my keys behind and I leave the room for a while. Maybe this is a feature that cannot be disabled on the key fob though?

**Comment by sylvek** [comment]
i think that is possible (by muting the keyring… but not yet implemented) but don't you loose the principal interest of this gadget? but by turning off the "background link" your wife should be less disturbed ;)

**Comment by sylvek** [comment]
in fact "background link" is a feature that allow to connect your iTag with your phone without having to launch iTracing2... the link is really in background when the bluetooth dongle is enabled.. if you launch the application and walk far of your itag, it should ring too.

**Comment by MDeeApp** [comment]
It is just another use case. I don't care leaving my tag behind. But I want the option to ring it in order to find it again.

That is why I bought a nut which does exactly (first I had the tag and was disappointed not having the option to turn off the out of alarm and also that it turn off if not connected for a few minutes) .

**Comment by sylvek** [comment]
yep.. but maybe some itag "clone" could do that.. some another not.
i don't believe that you can disable link loss without removing the physical link between your phone and your itag (but without, you could not bipping it)

**Comment by hosek** [comment]
Application for NUT tags allows user to create some "white areas" where alarm for connection lost is disabled (eg home, work, where you are often out of range) but this is a lot of efford, as this needs to be tracked at least by time (where you are at home) or better by GPS...

**Comment by sylvek** [comment]
With the mle15, removing a link between the device and the phone nicely or accidentally ring the device... So, we couldn't do this kind of feature with this model.

**Comment by sylvek** [comment]
Today I put an itag in my wallet.. Et when I go at work the bluetooth is going off (is based on my geolocation).. And it this case my itag doesn't ring if I go far it.. So.. I could power off/on the bluetooth based on location for example
