### ISSUE TITLE
Location and Bluetooth permission request comes together.

### ISSUE THREAD

**Issue by meanindra** [sylvek/itracing2#160]
I think it is annoying when I open the app and location and Bluetooth permission requests come together.
![Screenshot_20220103-184110_Settings](https://user-images.githubusercontent.com/36324543/147935448-456927b8-ab6a-475d-9e06-d05686184b0d.png)
**And can you add dark mode?**

**Comment by sylvek** [comment]
Hello @meanindra, you are absolutely right 🤔
The UI code is old, and i have only done minimal updates to be compatible with Android 10+
I'll think about how to improve it 🙏
