### ISSUE TITLE
Custom URLs not being GET'd

### ISSUE THREAD

**Issue by coire90** [sylvek/itracing2#167]
The feature to send a GET request to a custom URL does not seem to be working. I'm using itracing2 2.5.8.

I'm using a local http server on port 8080 to test and it's not receiving any requests from the app when the button is pressed on a tag. Or on double press, connect or disconnect.

My URLs looks like this:
http://127.0.0.1:8080/press
or:
http://127.0.0.1:8080/double
Etc.

The http server is fine because I can see requests made with browsers/curl. It seems the itracing2 app just isn't sending the requests.

**Comment by sylvek** [comment]
Hi @coire90 it's because you should not use "127.0.0.1" ip that is the "local loop" ip but instead :
- use a the public IP of your server
- or the local network IP (but before, you have to be sure that your phone and your server are on the same network)

**Comment by coire90** [comment]
As I said in my previous message, I'm running a *local* http server for testing. As in, the server *is* running on 127.0.0.1.  On the same device as itracing2. Sorry, I thought I was clear about that.

I'm well aware of the difference between local network, public and loopback IP addresses. Calling the same url from curl on the same device, or calling the url from a device on the same network (but obviously swapping the loopback interface IP for the LAN IP) works fine and I see the request on the server log output. But when I put the address in the custom url field of itracing2 and trigger it, the request is not received by the server. And presumably not sent since the server is verified to be working.

For my use case, I got it working using broadcast intents but I'd like to be able to have itracing2 send requests to 127.0.0.1:8080 for another use case where intents won't work. Also if this is a bug in your app, I'd like to be able to help you figure it out.

Thank you for the app btw. It's very useful. I only wish my cheap iTags were more reliable lol.

**Comment by sylvek** [comment]
👌 basically [the call is done by this code](https://github.com/sylvek/itracing2/blob/7d6f028e8e42269461e9a995947aa9f012c588c7/app/src/main/java/net/sylvek/itracing2/receivers/CustomAction.java#L135). it's pretty old now and maybe it doesn't work anymore with latest version on Android. What is your phone/android version ? 🤔

**Comment by MCSE-2000** [comment]
The custom action does not work. I want to send a GET to "http://192.168.9.15/cm=cmnd=Power%20toggle" to switch a TASMOTA, but it is not executed. The ringtone is played. 
The GET command executed in the browser works and TASMOTA switches.
I have a Moto G5 with /e/OS 1.12.3, equivalent to Android 11 with microG.

**Comment by sylvek** [comment]
@MCSE-2000 indeed, i've just done a test on my Google Pixel (Android 11) and it doesn't work 🤔
