### ISSUE TITLE
Hey, I've got a few suggestions!

### ISSUE THREAD

**Issue by Mixer2015** [sylvek/itracing2#17]
1. You can set the distance of the (exact).
2. be able to design the receiver auto-off time (often the receiver closed unwitting)
3. To increase the number of receivers (different needs)

4.The camera button functions can be increased of course better and better!

5.gps positioning (which is rubbish Chedan function, not required) no no no

**Comment by sylvek** [comment]
hi, i don't understand your post, sorry :-/
