### ISSUE TITLE
Unable to stop alarm

### ISSUE THREAD

**Issue by Rast1234** [sylvek/itracing2#18]
Hello. Looks like i've found a bug. Steps to reproduce:
1. have vibration alarm on two clicks
2. gps capture on single click
3. Double-click to start alarm. The only way to stop it is to click on notification
4. Now single click. It captures the position and replaces notification! Now you can't stop the alarm until you double-click again.

**Comment by sylvek** [comment]
ahh .. "bien vu" .. thks

**Comment by sylvek** [comment]
fixed
