### ISSUE TITLE
Adjust double-click latency

### ISSUE THREAD

**Issue by Rast1234** [sylvek/itracing2#19]
Is there a programmable way to adjust how fast double-click needs to be performed? I can do it 1 of 10 tries, others are recognized as single clicks :(
iTracing app recognizes my double-clicks fine.

**Comment by sylvek** [comment]
300ms .. yep i'm going to do something for that ;-)

**Comment by Rast1234** [comment]
thanks!

**Comment by sylvek** [comment]
fixed
