### ISSUE TITLE
Photography trigger 

### ISSUE THREAD

**Issue by currobravo** [sylvek/itracing2#2]
Allow trigger the camera button with the device button

**Comment by currobravo** [comment]
The original iTracing software allows it, but it requests so many rights that I have not installed it, I like yours more!

**Comment by sylvek** [comment]
Hello, 

I have done some tests but it just impossible without rewrite a camera app like inside itracing...  This camera app will too poorest.. :-(

But I wrote itracing 2 by sending intent when you click on button... I fact I try to find external app that allow to communicate with them by intent..

I tried to send a "camera button event" too but it's not allowed by Android os..

**Comment by sylvek** [comment]
http://developer.android.com/training/camera/photobasics.html#TaskCaptureIntent

A way?

**Comment by currobravo** [comment]
Sorry, I am not good in Android programing, but it sounds good for me :-/
It was just a suggestion for improve your great app. No idea how to do it.
Best regards.

**Comment by sylvek** [comment]
Don't worry thank you for your request. I'm going to watch how to do that.

**Comment by AlessandroBerta** [comment]
Take a look to other apps...    These apps have more feature bu don't recognize the device

**Comment by sylvek** [comment]
May you give me some links?

**Comment by AlessandroBerta** [comment]
Take a look at these...
http://www.hongkiat.com/blog/bluetooth-tracking-devices/

May you give me some links?

—
Reply to this email directly or view it on GitHub
<https://github.com/sylvek/itracing2/issues/2#issuecomment-131232090>.

**Comment by sylvek** [comment]
unfortunately the only way to do that is to add camera feature inside iTracing2 and i don't want that :(
(i checked all possibilities... emulate a key_volume_up / key_volume_down, check public intent, etc)

**Comment by AlessandroBerta** [comment]
Welcome back to this project. ;)

2015-12-29 9:44 GMT+01:00 Sylvek <notifications@github.com>:

> unfortunately the only way to do that is to add camera feature inside
> iTracing2 and i don't want that :(
> (i checked all possibilities... emulate a key_volume_up / key_volume_down,
> check public intent, etc)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sylvek/itracing2/issues/2#issuecomment-167747112>.
>



-- 

----

*Alessandro*

**Comment by sylvek** [comment]
i have never left ^_^ (i suppose)… but i have a couple of days front of me :P

**Comment by AlessandroBerta** [comment]
Lucky you...  ;)   i never find a couple of days to make some steps away in
my projects...

Have a nice day!
Il 29/Dic/2015 09:53, "Sylvek" <notifications@github.com> ha scritto:

**Comment by stanislav-brabec** [comment]
There is a possibility to do that easily on rooted devices. Application with root privileges can create input events. Tasker is capable to synthesize Camera Button event.

Well, Camera Button event does not work for some camera applications intended for devices that don't have camera button. But it is even possible to send a tap from Tasker: Run Shell, Command: "input tap {x coord} {y coord}", run as root. (In real life, you will need a more complicated task for it: Verify, that the camera application is in front, detect orientation, then create tap on a correct location of the shutter button.

See also issue #32.

I am just trying to use iTag for a very similar task: Use it as a button for Cardboard.

**Comment by stanislav-brabec** [comment]
Here is a manual, how to do it in a rooted phone with Tasker:

In Itracing2:
keyring actions / simple click action: call url or broadcast intent action
keyring actions / custom action: net.sylvek.itracing2.itag.button

In Tasker: Add profile: Event / System / Intent Received
Intent dialog:
Action: net.sylvek.itracing2.itag1.button
Keep the rest in default: None / None

Then it will ask to add task:
Input / Button: Camera

Save, Exit, fire camera applicatin, and take photos.

Tested with Camera FV5, LG G3 Camera application. Works in both.
