### ISSUE TITLE
App kill alarm?

### ISSUE THREAD

**Issue by Rast1234** [sylvek/itracing2#20]
Thank you for the great app! it's cool that you still making improvements! :)
I noticed that if i kill the app, phone still recieves signals from keychain. But the keychain starts beeping as if it lost the connection. Is it a feature? It can occur randomly (when app is killed to free RAM for example).
BTW is it guaranteed to work in background and after phone reboot?

**Comment by Rast1234** [comment]
Yay, it works after reboot!
Btw it's strange when phone and keychain both fire alarm when i power off the phone. It's good but unexpected.

**Comment by sylvek** [comment]
It's a feature, yes and no. 
A "service" retains a link between the itag and your phone. This service is launched if you activate the "background link". After booting, if you turn on the bluetooth feature (or your phone), this service starts..  (maybe the event of turning on is not broadcasted on some devices..) and the link is established bet

**Comment by sylvek** [comment]
Between your phone and your Keychain. At this time, you're not mandatory to launch itracing2. 
In other side, if you turn of the bluetooth feature (of your phone) or if you kill (brutally) the app. The link is broken and you Keychain will ringing. I added an option to not ringing the phone the team link is broken after a reboot or when the bluetooth feature is turning off.. But I tested this feature only on my Samsung.

**Comment by Rast1234** [comment]
thanks for explanation. Is version with this option released on play market, or i need to get it another way?

**Comment by sylvek** [comment]
I just have doing a test... My keyring doesn't ringing if I kill my app or turn off my bluetooth. 
Your itag don't have the same cheap of mine

**Comment by sylvek** [comment]
s/cheap/chip #lol

**Comment by sylvek** [comment]
Yes it's on Google play store.. (find "link is lost on power off ")
