### ISSUE TITLE
tuning 'out of range' trigger

### ISSUE THREAD

**Issue by thejus89** [sylvek/itracing2#21]
Hi, 

Its great that you have included the rssi measure . Is there a possibility to modify the alarm function for 'out of range' option where one could pre-set the range?

**Comment by sylvek** [comment]
It's a good idea!
But I am really disappointed about this measure dropping 80 to 20% without
moving... With my itag

**Comment by thejus89** [comment]
Oh. I see . My itag is working fine . If you could provide an option of setting an alarm if the rssi level goes lower than 30 to 35 percent then it should serve the purpose, I guess.
P.S : I was checking the rssi while keeping the itag static and found that value.

**Comment by thejus89** [comment]
Also, there might a tiny possibility that the battery in your itag is drained out . It may cause the rssi to vary abruptly.

**Comment by thejus89** [comment]
Or even the better option is to set a variable rssi option where the user can determine the rssi level for the out of range alarm.

Sorry for flooding you with so many suggestions :D ;)
