### ISSUE TITLE
Continous busy symbol

### ISSUE THREAD

**Issue by ernstjanmeijer** [sylvek/itracing2#24]
Today I downloaded and installed the app on Jiayu S3 Android. After initial succes, it now seems to be in an infinite loop. As it just displays the spinning sign continouly. Stopping and restarting the app has no effect. Only clearing the data and reconnecting works.

**Comment by ernstjanmeijer** [comment]
It seemed that the itag was turned off. After turning on the itag again, it automatically connected.

**Comment by sylvek** [comment]
@ernstjanmeijer great! \o
