### ISSUE TITLE
GPS fences 

### ISSUE THREAD

**Issue by Heistergand** [sylvek/itracing2#26]
It should be possible to set up geo fields on the map and link them to a set of actions, whereas an action can be switching a setting. Thus it would be possible to disable alerts at home, trigger an action when leaving home without the tag, or choose a silent form of alert when at work while having it very loud when at shopping mall.

**Comment by bluish-x** [comment]
Even though this would be great, I think this enhancement may depend on Google Services Framework and may prevent installing the app or cripple the user experience for those who don't have Google's apps on their devices.

**Comment by lambdaupb** [comment]
I think this is better handled by one of the usual Task automation Apps like Automate by llama or Tasker. Configure a broadcast Intent on button action and receive it in the Taker app and decide there what to do, maybe based on location and other variables.

**Comment by sylvek** [comment]
Not so bad.. Personally, I never used Tasker.. What you described works already?

**Comment by lambdaupb** [comment]
I'm currently trying to get broadcast Intents to work, I installed `Intent Intercept` and entered `itracing2.single` but the Intent is not captured. Have you tested the Intent custom action?

In general this should work well.

**Comment by lambdaupb** [comment]
So I entered `android.intent.action.CAMERA_BUTTON` as the custom action and that launches the camera app. So there is probably just something wrong with my setup.

**Comment by sylvek** [comment]
\o/ that's a good news!

FYI, this portion of code (https://github.com/sylvek/itracing2/blob/master/app/src/main/java/net/sylvek/itracing2/receivers/CustomAction.java#L61) describes how the intent is broadcasted.

**Comment by lambdaupb** [comment]
![automate_flow](https://cloud.githubusercontent.com/assets/1890613/25229423/78714f38-25d0-11e7-90f6-21fb7b99af98.jpg)

To receive the Intent in llama Automate, the `Broadcast Receive` action needs to be configured as in the screenshot. The URL SCHEME needs to be switched to manual and left empty and the action switched to manual and the Intent string entered with quotes.

**Comment by sylvek** [comment]
nice job :)
