### ISSUE TITLE
Won't trigger remotely - one way tigger

### ISSUE THREAD

**Issue by robforrester** [sylvek/itracing2#29]
I have several MLE-15 devices. The black ones work. The white ones will alert the device, but the device won't alert the phone. Any ideas?

**Comment by sylvek** [comment]
Maybe there is a misfunction and that your white device can not ring?

**Comment by robforrester** [comment]
I have 3 black and 2 white. The black ones work, the white ones will alert from the phone to the device, so the devices (white) beep, but when you press the button they don't do anything on the phone. If it was just one I'd think a faulty device, but both white ones behave the same. If I use the white ones with etracing app they can take pictures on the phone by using the button, etc.

 
 
  On Sat, 26 Dec, 2015 at 7:13, Sylvek<notifications@github.com> wrote:   
Maybe there is a misfunction and that your white device can not ring?

**Comment by sylvek** [comment]
Humm strange! It's unbelievable that black and white have not a similarly hardware. But you can check this easily by using a software named "nNF master panel control" on the play store.
Play with this app and maybe you will find what's wrong.

**Comment by sylvek** [comment]
Please try my last beta version.. You will find it on the topic "multi devices support"
