### ISSUE TITLE
terrible product

### ISSUE THREAD

**Issue by urshitsucks** [sylvek/itracing2#30]
Ok well first I can never connect and Second Life the fog is always turning off by itself I can never get it to work unless I'm sitting there side by side pressing the button the range on this thing I can't even walk to my bathroom which is only 15 feet away

**Comment by sylvek** [comment]
And?

**Comment by urshitsucks** [comment]
And what that's about it how can u close it if u did nothin

**Comment by sylvek** [comment]
ton commentaire est de la merde. Au lieux de te plaindre, essaie d'améliorer le logiciel en ayant une approche constructive.

regards.

**Comment by urshitsucks** [comment]
English
