### ISSUE TITLE
Custom action does not work

### ISSUE THREAD

**Issue by stanislav-brabec** [sylvek/itracing2#32]
I just wanted to test Custom action (in both stable and testing version), and I see no response from the application. If I set it to vibrate, it works. If I set custom action, nothing happens, both with empty custom action and custom action with http://some_url

I see several problems here:
1) Custom actions are never called.
2) Even if they would be called, the current implementation makes hard to implement different action for single and double click. Ideally, custom action should be definable separately for single and double click.
3) The custom action code itself is bad: Empty custom action should generate broadcast intent. Action starting with http:// or https:// should open URL. All other URIs are ignored. It makes impossible to define  Tasker URL Launcher style URIs like tasker://iTagClick.

**Comment by sylvek** [comment]
Well I took time to understand... It's the opposite. This action call an
URL in background without having response. In my case, it calls a link in
my internal webserver to do something on it.

Le mar. 29 déc. 2015 17:44, Stanislav Brabec <notifications@github.com> a
écrit :

**Comment by stanislav-brabec** [comment]
Thanks for explanation. It was not clean that it does not call Android Open URI, but that it silently calls HTTP GET.

Implementing of Android Open URI or sending intents could be very useful: Open application, doing some actions. But it is possible to implement this feature using Tasker using the current intent feature.

I was now able to notify Tasker by intent:

Set custom action in Itracing2: net.sylvek.itracing2.itag1.button

In Tasker: Create Intent Event receiver with: Action: net.sylvek.itracing2.itag1.button / None / None

Then associate action you need.

Feel ree to close this as invalid. But please consider implementing different custom action for single and double click.

**Comment by sylvek** [comment]
:+1:

**Comment by sylvek** [comment]
@stanislav-brabec may you share your work?

**Comment by stanislav-brabec** [comment]
Feel free.

Here is a better version:
https://drive.google.com/open?id=0B3bBkgjXNnUyYVB5bnM5eUVWZUk
(more could be available: https://drive.google.com/open?id=0B3bBkgjXNnUyaEQtOTF0ZDdJclk)

If features application in front based switching. It is easily customizable for anybody needs.
Please let me know if there are any problems. It is a hand edit of the exported project XML.

Note that input emulation needs root privileges.

**Comment by stanislav-brabec** [comment]
Tips for improving your code:

For Tasker control, arbitrary name of the broadcast intent is an overkill.

The button broadcast could have following unique id:
net.sylvek.itracing2.{tag id or tag#}.{button|doubleclick|lost}

**Comment by sylvek** [comment]
Your last message talk to me...
It should be very easy to broadcast a public intent on click/double
click/etc... Good point.
If I well understand.. I will add that tomorrow morning.

Regards.

Le jeu. 7 janv. 2016 17:55, Stanislav Brabec <notifications@github.com> a
écrit :

**Comment by stanislav-brabec** [comment]
Yes, you understand correctly.

Don't forget to add tag identification to the broadcast string, as your application now supports more tags.

At least for Tasker, configuration-ability of the broadcast name is not needed. (I don't know, whether intent broadcast with arbitrary string has any potential use.)

**Comment by sylvek** [comment]
added on the last beta release (2.0.10)
D/class net.sylvek.itracing2.BluetoothLEService(14910): onCharacteristicChanged() - simple click
D/class net.sylvek.itracing2.BluetoothLEService(14910): onCharacteristicChanged() address: 08:7C:BE:00:F4:2F - sendBroadcast action: net.sylvek.itracing2.action.simple-click
