### ISSUE TITLE
tag starts to beep on high Android load

### ISSUE THREAD

**Issue by stanislav-brabec** [sylvek/itracing2#33]
When I enable background link, the tag often starts to beep when Android is under a heavy load: Large copy, Google Earth running etc.

I suspect that the itracing2 service is being killed and connection is closed.

I think that you need to prioritize the application somehow, or make the application running in "foreground", i. e. adding a persistent notification or notification area icon.

**Comment by sylvek** [comment]
i noticed the same "issue".. prioritising a service is not a good practice and prevents nothing much if your phone is under water.

> A started service can use the startForeground(int, Notification) API to put the service in a foreground state, where the system considers it to be something the user is actively aware of and thus not a candidate for killing when low on memory. (It is still theoretically possible for the service to be killed under extreme memory pressure from the current foreground application, but in practice this should not be a concern.)
Note this means that most of the time your service is running, it may be killed by the system if it is under heavy memory pressure. If this happens, the system will later try to restart the service. An important consequence of this is that if you implement onStartCommand() to schedule work to be done asynchronously or in another thread, then you may want to use START_FLAG_REDELIVERY to have the system re-deliver an Intent for you so that it does not get lost if your service is killed while processing it.

**Comment by stanislav-brabec** [comment]
Yes, there is no guarantee, that the service will never be killed, but it could make it ocurring less often.

Today the tag started to beep just in the middle of the night. On a device with 3 GiB RAM!

Killing Itracing2 should be prevented as much as possible, as it makes the app unusable in a real life.

**Comment by stanislav-brabec** [comment]
I found this article on a similar issue: http://stackoverflow.com/questions/7408212/high-priority-android-services

**Comment by sylvek** [comment]
Okay... I'm surprised because I didn't seen this issue with my new phone (s6 edge). 
What is your phone? And.. Do play games or whatever?

Bonne année !

**Comment by stanislav-brabec** [comment]
My phone is LG G3, 3 GB version. No games.

It happens regularly in Google Earth for Cardboard (I made a Tasker task converting itracing2 button press intent to screen tap and using the tag to control the app. Button stops responding, and tag starts to beep.)

And it happens sometimes even when the phone is sleeping (and me too).

I have more apps installed, and either OOM or running process limit killer terminates it.

Well, I also have Greenify paid with enabled feature of timer batches for all apps. (itracing2 is not included in the list of greenified apps.)

Anyway, option to make itracing2 a high priority task would be welcome. (The notification could have a button to disable background links for all tags.) It is not a 100% guarantee, but it works very well on phones that are not overloaded. For example, Tasker is much larger app, which uses high priority service. Looking at logs, it was never killed by Google Earth Cardboard edition. (But it was killed many times on my old phone with 500 MB RAM.)

**Comment by sylvek** [comment]
please check the beta version and tell my if it's better => https://play.google.com/apps/testing/net.sylvek.itracing2

**Comment by stanislav-brabec** [comment]
Well, it is better, but not OK. I experienced some strange things.

Testing with Google Earth for Cardboard, with iTag used as tap emulation (itracing2 sends broadcast intent, intent is received by Tasker, task is launched, it starts root shell, this root shell calls input command, and it emulates tap). I experienced one connection loss with beep started. In older version, this triggered beeping many times.

Testing with standard Google Earth, iTag remains idle. I experienced two connection losses as well. But I am sure, that the icon does not disappear even for fraction of second. In the second case, the tag continued to beep, even if itracing2 was in front.

itracing2 crashed during my test many times (I always sent the crash report).

But I experienced some surprises:

The crash of itracing2 sometimes caused tag beeping. It is expected.

But at least once the crash did not cause any beeping. It is very surprising.

adb shell commad "ps | grep itracing" shows only one itracing process running.

Now I am testing the idle phone with tag on for longer time.

**Comment by sylvek** [comment]
ok thks, i just finished a test during 1h (without setForeground) and i had 2 devices beeping (one time each) oO i'm going to retry with setForeground..

**Comment by stanislav-brabec** [comment]
I got first beep with testing version while idle after 12 hours. Phone was standing in the wireless charger stand, so I have no logcat.

**Comment by stanislav-brabec** [comment]
It could be a problem of Android BLE stack. I was just after the beep unable to connect to BLE based Xiaomi Mi Band. I had to turn off/on the Bluetooth.

**Comment by sylvek** [comment]
Yep... Maybe. I have a mi band too.. No problem with my S5 and S6.

Le mer. 6 janv. 2016 00:15, Stanislav Brabec <notifications@github.com> a
écrit :

**Comment by sylvek** [comment]
i close this issue.. i added an option in beta version. thank you!

**Comment by stanislav-brabec** [comment]
It now looks well with one exception: Application upgrade in Google Play. I don't know, whether it is technically possible to something with it.

My extended 40 hours testing has following results:
Once: Crash of LG Bluetooth Smart Settings
Once: Freeze of Bluetooth Stack
Once: Application auto-upgrade in Google Play

**Comment by sylvek** [comment]
I guess that the auto upgrade will work when I will release to "stable" the
beta version..

Le jeu. 7 janv. 2016 18:00, Stanislav Brabec <notifications@github.com> a
écrit :
