### ISSUE TITLE
Putting iTracing2 in F-Droid

### ISSUE THREAD

**Issue by bluish-x** [sylvek/itracing2#39]
That would be really great if you could put the iTracing2 in F-Droid's repo.

For those who don't know about F-Droid; taken from wikipedia.org/F-Droid:

F-Droid is a software repository (or "app store") for Android applications. The main repository, hosted by the project, contains only apps which are free software. It works similarly to the Google Play store.

https://f-droid.org/

**Comment by sylvek** [comment]
Itracing2 uses some Google lib.. Is there a problem with that?

**Comment by bluish-x** [comment]
It should be okay as long as its licence is compatible with gpl2. Besides I couldn't find "google" string in itracing2's repo. Which of google's libs do you use with itracing2? 


https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses

**Comment by sylvek** [comment]
Essentially the compatibility libs from Google

**Comment by bluish-x** [comment]
I am not a lawyer but I believe it should be okay.
Check Kernel Adiutor out. It is on F-Droid too.
https://github.com/Grarak/KernelAdiutor

**Comment by sylvek** [comment]
That sounds good

**Comment by sylvek** [comment]
Proposal done

**Comment by juanjgit** [comment]
What happened? ITracing2 is not in F-Droid

**Comment by sylvek** [comment]
If you want you could put on it.

**Comment by sylvek** [comment]
https://gitlab.com/fdroid/rfp/-/issues/1964
