### ISSUE TITLE
No more ring on smartphone

### ISSUE THREAD

**Issue by AlainDu** [sylvek/itracing2#40]
It was working correctly during one month until a few days ago.
Software see Itag et I can do the ITAG ringing, but neither clic nor loss of connection make ring on the smartphone, but the iTAG ring. What happen ?

**Comment by sylvek** [comment]
Huummm.. What version do you have. Do you remember if you upgrade itracing2 before this issue?

**Comment by AlainDu** [comment]
Hi!
Version is 2.0.12 . I think there were an upgrade a few days ago, just before this issue.
Thank’s

**Comment by sylvek** [comment]
Do you have checked the box on the right your device name (on the devices list)?

**Comment by AlainDu** [comment]
Of course it is on. All is working except ring on the smartphone when it lose the signal. 
I made a mistake in my first message, when I click on the Itag the smartphone ring. It was just because I had put the ring on double click and the double click don’t work very well.
Have a nice day.

**Comment by sylvek** [comment]
i have done a test this morning with the released version .. i've just tested the simple click but everything goest all right .. maybe you could try the beta version?
https://play.google.com/apps/testing/net.sylvek.itracing2

**Comment by AlainDu** [comment]
The problem occur only at the signal lost. I'll try the beta version today.

Sent from my ASUS

-------- Message d'origine --------
De :Sylvek <notifications@github.com>
Envoyé :Wed, 03 Feb 2016 10:09:53 +0100
À :sylvek/itracing2 <itracing2@noreply.github.com>
Ci :AlainDu <onclealaind@free.fr>
Sujet :Re: [itracing2] No more ring on smartphone (#40)

**Comment by sylvek** [comment]
thks, i will do a test this evening

**Comment by sylvek** [comment]
Test done with the version 2.0.12.. Everything goes all right.

**Comment by AlainDu** [comment]
Hi!
Its works again fortunately, whith some problems yet. It seems this trouble come from a new device (old headphone) I tried to connect, it did’nt work, then I killed the device in parameters/bluetooth.
Yesterday I have connected the device DTVBluetooth by the same way and it works again, but...

There is yet some troubles because your application lose the signal sometimes and the device bip. I have to press the device button several times to connect again.

I tried a new iTag, it’s more difficult to understand : once the device bip but not the smartphone, another time neither bip nor smartphone but the meesage on smartphone “arrêter la sonnerie”.
It seem there is problem of stability in bluetooth connection. 

I hope this can give you some indication for the software. 

Do you know if it is possible to clear all bluetooth data without erasing all the smartphone data ?

Anywhere, thank you for your courtesy.

Your’s faithfully

Alain DUVAL (PARIS)

**Comment by sylvek** [comment]
Hey... There an option that you could use.. On the front page.. Go to preferences menu (top right) and select foreground option.. An icon will appear but the connection should be better.
I close this issue because the main trouble is over.
