### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by eng-marani** [sylvek/itracing2#47]
Since last update:
Pressing on a keyring entry application quits
Unable to remove entries (Long press only expose a rename action)
When attempting to press "ring keyring" button, a message appear: something goes wrong.

This app is a fake. iTracing standard app is terrible too, bit at least see and control eTag devices

**Comment by sylvek** [comment]
hi @eng-marani i saw that.
if you remove-reinstall the app, that should fix the problem
i looked the stacktrace on android store and fix the issue.

**Comment by sylvek** [comment]
my bad, i just watch that my previous fix is not perfect :-/
sorry for that.

**Comment by sylvek** [comment]
fix with the last version (2.2.3)

**Comment by eng-marani** [comment]
Trying to uninstall/reinstall, i'll give you feedbacks soon ;o)
Also, i'm able to export adb debug/logtrace if you are interested to look into that.

**Comment by eng-marani** [comment]
Ok, i have updated... VERY BETTER NOW.
I can pair again, but there are several UI troubles i would like to feedback you.
I want to help you improving the usability of UI interface.

**Comment by eng-marani** [comment]
Long-press -->  Button "RING THE KEYRING".
It will start to beep, but there is no way to turn off the beep unless resetting the device.
To avoid disturbing people when you activate this test option, please change the button to "STOP THE KEYRING" after activating. The same into main keyring window with the little icon on bottomright (with a little loudspeaker). This can be pressed again to stop ringing, but it is not obvious, because the icon is exactly the same. Please change the icon so user is informed that it can be pressed again to stop.

Another little thing... if you rename your device, please show that name on top instead of the bluetooth ID, nobody care about that ID except developer. Also, a little bitmap would be welcomed, like in stock iTracing

**Comment by eng-marani** [comment]
Simple/Double click option ---> DOES NOTHING
Also, options available should be mutually exclusive (option buttons, not checkboxes) to avoid confusion

**Comment by sylvek** [comment]
strange.. i tested with success yesterday.. a double-clic to start ring and single click to stop it :-/

**Comment by eng-marani** [comment]
If i turn off the tracker, and then turn on again after few seconds, it does not reassociate (the big green circle is empty). I need to UNFLAG then REFLAG the device in order to make it work again

**Comment by eng-marani** [comment]
I confirm that the tracker button have no effect both on "simple click" and on "double click" operation. It was working few weeks ago.

**Comment by sylvek** [comment]
hey, i just tried a single click (ring on) -- double click (ring off) -- loose connection (vibrate) with success.. you should be more patient during the bonding between your iTag and your phone :-/
(or send me your traces)
what it the original name of your itag "mle-15"?

**Comment by eng-marani** [comment]
Hi, i have sent you a small donation via PayPal to support your work. Rarely a developer is so responsive like you.

**Comment by eng-marani** [comment]
Please, can you tell me how do i find the itag name ?
I have used a BLE sniffer, and the iTag device exposes some informations as well
(PRIMARY SERVICE)
MANUFACTURER NAME STRING = CEVA
MODEL NUMBER STRING = BT 4.0
FIRMWARE REVISION STRING = 01.1
HARDWARE REVISION STRING = SM-1

But found no name like yours

**Comment by sylvek** [comment]
thks @eng-marani ! i'm going to release a version with some fixes…
the name that i look for is "ceva" .. first time that i read this manufacturer oO

**Comment by eng-marani** [comment]
It is a pure CRAP! bought from Groupon shopping. Several times i had to remove battery in order to make it to work again. I suspect they are unreliable. But it was working with your tool before. It now connects but pressing the key do nothing (the original buggy iTracing still do work)

**Comment by sylvek** [comment]
okay.. if you're used to read adb log… you could trace the BluetoothService
please do something like that => $ANDROID_HOME/platform-tools/adb logcat | grep itracing2
and play with your itag.. send me the result.

**Comment by sylvek** [comment]
please try the version 2.2.5… send me your traces in an another issue and i'll check it :)

**Comment by sylvek** [comment]
@eng-marani check this wiki page => https://github.com/sylvek/itracing2/wiki/Contribuate--by-reading-traces-:)

**Comment by eng-marani** [comment]
Hi Sylvec, i have collected the trace, how can i forward the zip to you ?

**Comment by sylvek** [comment]
@eng-marani yes! please send me it to smaucourt@gmail.com
