### ISSUE TITLE
Button actions doesn't work

### ISSUE THREAD

**Issue by Jesus-M** [sylvek/itracing2#52]
I've configured everything right, or I think so, but nothing happens when I click the button.

APP release: 2.2.9
Android release: 5.1.1
Kernel: 3.10.49 

I've tried both background and foreground ways.

**Comment by sylvek** [comment]
May you take a screenshot of your selected actions for the single click?

**Comment by Jesus-M** [comment]
https://www.dropbox.com/s/tgip5hwjmo06diu/2016-03-19%2017.00.37.png?dl=0

**Comment by sylvek** [comment]
ok thks .. very strange :-/
may you try the "beta" version and take a screenshot of "events history" tab. (new feature)
after playing with your iTag? (what kind of phone do you have?)

beta link => https://play.google.com/apps/testing/net.sylvek.itracing2

**Comment by sylvek** [comment]
make sure that the checkbox on the right of the devices list is checked for your device.. if not.. you can interact with your iTag only when you are on the device dashboard

**Comment by Jesus-M** [comment]
OK, I'll try the beta.

My phone is a BQ M5

I'll let you know about beta tests.

**Comment by Jesus-M** [comment]
Nothing happens and nothing is recorded at event history.

https://www.dropbox.com/s/2cfvywovc62slxa/2016-03-19%2017.23.48.png?dl=0

https://www.dropbox.com/s/ly4xaf91hq3vutp/2016-03-19%2017.24.01.png?dl=0

If I click on the speaker icon of the app, the keyring bleeps until I click
the speaker again.

So, the communication is ok, but only from the phone to the iTag.

Regards

**Comment by sylvek** [comment]
okay.. and if you go back de ton home screen (may you take a screenshot too?) et return to the event history?
may you take a pic of your iTag?

**Comment by Jesus-M** [comment]
Well, actually I've seen records on the event history, but only when I
click the icon on the APP.

https://www.dropbox.com/s/a6ceo31ygogg5ut/2016-03-19%2017.31.14.png?
<https://www.dropbox.com/s/a6ceo31ygogg5ut/2016-03-19%2017.31.14.png?dl=0>dl
<https://www.dropbox.com/s/a6ceo31ygogg5ut/2016-03-19%2017.31.14.png?dl=0>=0
<https://www.dropbox.com/s/a6ceo31ygogg5ut/2016-03-19%2017.31.14.png?dl=0>

Now, what you asked:

https://www.dropbox.com/s/tbzejjsuuup7x1c/2016-03-19%2018.33.35.jpg?dl=0

https://www.dropbox.com/s/7wna8pqtl48yy6h/2016-03-19%2017.34.03.png?dl=0

(The JM is because I added an extra tag to identify the keyring)

Thanks

okay.. and if you go back de ton home screen (may you take a screenshot
too?) et return to the event history?
may you take a pic of your iTag?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/sylvek/itracing2/issues/52#issuecomment-198753084>

**Comment by sylvek** [comment]
ok thanks! everything seems alright…
heard you a sound when you clicked on your iTag?

**Comment by Jesus-M** [comment]
I heard a sound (a bleep) in the iTag, but not in the phone.

2016-03-19 18:43 GMT+01:00 Sylvek <notifications@github.com>:

**Comment by sylvek** [comment]
okay.. may you uncheck all actions and re-check it? .. and try..

**Comment by Jesus-M** [comment]
Done, but unsuccessful :(

**Comment by sylvek** [comment]
okay :( .. may you extract traces ?
https://github.com/sylvek/itracing2/wiki/Contribuate--by-reading-traces-:)

**Comment by Jesus-M** [comment]
Sorry, I've never gotten to run ADB on my Linux desktop. I know it should
be easy, but I can't do it :( (maybe my Linux kernel is too old -3.10.17).

2016-03-19 19:07 GMT+01:00 Sylvek <notifications@github.com>:

**Comment by sylvek** [comment]
obviously .. everything goes right on my phone.. humm... try a last option.. may you activate the foreground mode ? (in the preferences option - on the first screen)

**Comment by Jesus-M** [comment]
I did, with same result :(

What I've observed now is that the events history shows an 'out_of_range'
event, but the keyring is just few centimeters from the phone. The blue led
on the keyring was blinking. I've started your app, click on the keyring
name, and the led stopped. Nothing new at events history after that.

Regards

2016-03-19 19:47 GMT+01:00 Sylvek <notifications@github.com>:

**Comment by sylvek** [comment]
oohh .. okay! that's why :)
(i suppose your device loose the connection)
you could add an action on "connection" and another on "out of range".. the events history should populate itself.. how do you make your test?

**Comment by Jesus-M** [comment]
No, that is not the problem (I think at least the whole problem), because
with the app open (so, the link established) the click on the keyring
doesn't produce any efect neither.

But anyway I've set an action for the connect event, and despite I see the
event just twice on the history the phone is vibrating again and again (the
action I chose).

And I don't see any disconnect or out_of_range event (apart the only one
I've seen and I told you earlier)

2016-03-19 19:55 GMT+01:00 Sylvek <notifications@github.com>:

**Comment by Jesus-M** [comment]
Anyway, nevermind, probably it is because of my specyfic phone. I'll
uninstall the app.

Thanks for your help.

2016-03-19 19:55 GMT+01:00 Sylvek <notifications@github.com>:
