### ISSUE TITLE
This does not do anything

### ISSUE THREAD

**Issue by davebonini** [sylvek/itracing2#56]
ARE THERE INSTRUCTIONS ANYWHERE...CANNOT PAY YOU IF THIS DOES NOT WORK.

**Comment by sylvek** [comment]
Hello I had any wiki pages... Maybe not enough clear.. Please, could you tell me more.. And I will update the instructions. 
Regards

**Comment by davebonini** [comment]
Hi Sylvek,

I finally am learning your software.  The iSee device never worked, so I
was not sure what was supposed to happen.  Through trial and error, I am
beginning to understand how to use the features.

I hope to send you ideas for better instructions later.  I hope they will
help you.  And, I am sending you $5 USD.

Where are you located?

Be Well,

Dave Bonini
925.685.4532

**Comment by sylvek** [comment]
Hi thanks!
Sorry for the delay, I live in France.

Regards
