### ISSUE TITLE
Live Map?

### ISSUE THREAD

**Issue by TomZilla1** [sylvek/itracing2#58]
Is there a live map feature? I know there's the "record location" on connect / disconnect. But it would be nice to have a live map of where the MLE-15 device is.

**Comment by sylvek** [comment]
humm .. please tell me your use case :)
the itag doesn't contain neither a gps nor a cell chip
so the only way to track an itag, is to use a phone.. but.. why not should we track the phone instead?

**Comment by TomZilla1** [comment]
Is there a way to get the distance and angle of direction from the
Bluetooth signal from the MLE15?

**Comment by sylvek** [comment]
Non only the strength and this measure is in dbm without knowing a reference measure.. So it is difficult to calculate in meter the distance between an itag and a phone
