### ISSUE TITLE
Bathroom

### ISSUE THREAD

**Issue by TomZilla1** [sylvek/itracing2#59]
When I goto the bathroom with my phone, the keychain beeps (because it is out of range). Is there a way to disable that? I'm fine if the phone vibrates, but don't want keychain beep.

**Comment by sylvek** [comment]
Hey! .. two solutions.. do not take a shower .. of .. use a hammer.
more seriously.. there is no way to disabled the beeping from the keychain :-(
(or i didn't find it)

**Comment by TomZilla1** [comment]
I see. Must be a hardware thing. Thank you though! Great program. The only
working one on Google Play.
