### ISSUE TITLE
iTag bug

### ISSUE THREAD

**Issue by mofosyne** [sylvek/itracing2#6]
For this [tag](http://briankhuu.com/blog/self/hardware/2015/10/27/cheap-ebay-ble-tag-teardown-itag-via-itracing-app.html) there is some issues:

* Battery value not shown (even when clicked)
* Ring keyring not avaliable
* Button click doesn't seem to work
* Link loss does seem to work. (Btw the tag volume is not very loud)

below is the screenshots, of both the gatt of the tag, and the app interface showing the greyed out ringing.

## app screen

![2015-10-27 15 15 01](https://cloud.githubusercontent.com/assets/827793/10762388/f8d807a4-7d19-11e5-8450-15bded7a6fec.png)

### immediate alert
![2015-10-27 15 18 51](https://cloud.githubusercontent.com/assets/827793/10762475/4f8d2142-7d1a-11e5-916d-c5beb2150352.png)

### button?
![2015-10-27 15 18 33](https://cloud.githubusercontent.com/assets/827793/10762474/4f8ca9a6-7d1a-11e5-9ab6-5cf36e997f46.png)

### battery
![2015-10-27 15 14 22](https://cloud.githubusercontent.com/assets/827793/10762387/f8acd2f0-7d19-11e5-8fcc-25ad2a76c5d0.png)

**Comment by sylvek** [comment]
Hi!

what is the brand of your phone?
service ids seem correct, however i suppose that you have the same trouble that another users...
look this file, prefix uuid matches
https://github.com/sylvek/itracing2/blob/master/src/net/sylvek/itracing2/BluetoothLEService.java

**Comment by mofosyne** [comment]
HTC M7 is the phone I got

**Comment by hosek** [comment]
Hi, would you mind to test this build if its working with your device?
https://drive.google.com/file/d/0B0xPH953MoR6cWFoRFIxdFhCMDA/view?usp=sharing
Thanks

**Comment by sylvek** [comment]
Ok for me

**Comment by paskalip** [comment]
Works with mine as well, well done!

I get battery and rssi info, and I can program the single click and out of range functions. Double click doesn't work (registers as multiple singles) and the capture my position does nothing. Lastly, ringing the keyring works ok but there is no way of turning it off unless I shut it down completely (the keyring). 

On another note, how difficult is to code a custom function for the keypress (like select what to execute instead of ringing the phone)

**Comment by sylvek** [comment]
the delay between 2 clicks must be lesser than 300ms (my twin girls played too much with my keyring…)

**Comment by sylvek** [comment]
>the capture my position does nothing

depends of your phone configuration.. do you have network/gps enabled?
the code looks for a position aged of 10s max.
if not found, it requests a position … (GPS or NETWORK if enabled) and when the position is going, a notification is displayed... but if you use only GPS and you are at home for example, you will see nothing.

**Comment by sylvek** [comment]
>Lastly, ringing the keyring works ok but there is no way of turning it off unless I shut it down completely (the keyring).

on my iTag, the ring stops after 20sec..

**Comment by sylvek** [comment]
>On another note, how difficult is to code a custom function for the keypress (like select what to execute instead of ringing the phone)

it is not really hard (if you know android sdk, i simple call an intent…)
but the difficulty is more around that.. example: i would like to send an email with a custom text .. where to store this custom text to launch automatically this email?

**Comment by paskalip** [comment]
I'll answer going backwards

Well, if you get an option to select an app or an action, then with tasker, ifttt or a similar app you can do all sorts of things.

Ring didn't stop for 1+ minute

I'll try to fiddle a bit more with the location capture. It's strange as I didn't see it starting the gps or requesting a position (in kitkat you can't force the gps to be active in the background so every time there is a location request there is the location marker on the notification area)

Double clicks didn't register, even in less than 300ms. I just got multiple single clicks

**Comment by hosek** [comment]
You probably have tag like mine... MLE-15 and yes, you have to turn it off to stop beeping, application send High alarm request to keyring, I thought that this could be a problem (high - endless alarm and meduium - short alarm) but after changing the alarm level to Medium alarm, it does nothing.
Sylvek's tag seems to be more sophisticated and "mature", than those chinese copies...

**Comment by paskalip** [comment]
Yes, that's right. Using the nRF Control (the app that sylvek suggested in the other thread for this) that discovers the services of the keyring I was able to identify the medium and high alarm. Indeed the medium did nothing but sending ether a medium or a none stops it. So instead of stopping it from the keyring why not add an extra function in the app to stop it?

**Comment by hosek** [comment]
Yes, mutting it from the application side sounds good!

**Comment by sylvek** [comment]
@paskalip yes it should be an option.. but so.. the apk of @hosek is ok for you too?
if yes, i should create a new version with his wonderful job :)

**Comment by paskalip** [comment]
Apart from the issues I mentioned above, yes, it works!

**Comment by sylvek** [comment]
good!

**Comment by paskalip** [comment]
Although, it does take an awful lot of time to register the keyring. Sometimes I have to clear the app data to get it to connect again. Sometimes I need to restart the keyring 2-3 times. And sometimes it just works. But this might as well be a hardware issue (yay cheap clones)

**Comment by mofosyne** [comment]
@hosek it works. I can ring the keyring, but I can't stop it from ringing.

Battery info is showing.

Single button works

Double button only seen as single click

---------

So is there any location where we can find the GATT definitions of these tags?

**Comment by mofosyne** [comment]
also, I really like the idea of sending out urls or intent based on a press of a tag.

I can imagine putting one in strategic location to press as needed, e.g. empty coffee... but that is somewhat hampered by the fact you can only connect one device at a time. 

Might be more useful to have an BLE beacon with button instead.

**Comment by paskalip** [comment]
so, location capture is indeed working, just takes a bit of time. Now that I saw it, I have a question. How on earth is useful to get a notification with my mobile's location on my mobile??? Not to mention that I get that only if my phone is in range with a bluetooth button...

**Comment by hosek** [comment]
I never tried it, but imho this should be last location where the keyring was connected to your phone... you forgot or mute the alarm, but just see, that last time your device was connected was in the garden... so know where start searching:) Bad that MLE-16 turn itselfs off after while... 
I like the case - let something with keyring at home and everytime Im near, it automatically connect to the app so I could trigger the alarm and find it... but this seems to be imposible with this chinese tag

**Comment by sylvek** [comment]
>also, I really like the idea of sending out urls or android intents (to launch apps, and perform certain actions) based on a press of a tag.

>I can imagine putting one in strategic location to press as needed, e.g. empty coffee... but that is somewhat hampered by the fact you can only connect one device at a time.

>Might be more useful to have an BLE beacon with button instead.

indeed, the IBeacon technology is better suited for this kind of thing

**Comment by sylvek** [comment]
>so, location capture is indeed working, just takes a bit of time. Now that I saw it, I have a question. How on earth is useful to get a notification with my mobile's location on my mobile??? Not to mention that I get that only if my phone is in range with a bluetooth button...

;) i asked me the same question… in fact, some users asked me to add this feature because they add the keyring on their bag and want to be informed if the bag is forgotten somewhere. Others let the keyring inside their cars, and it's a good way to get the park location automatically ..

You're right .. supporting several iTag is a huge feature

**Comment by sylvek** [comment]
guys.. i released a new beta (containing @hosek code's but remastorized)
https://drive.google.com/file/d/0B2WJ90QJfme5SVMzZ3J6aDNqX2c/view?usp=sharing

**Comment by paskalip** [comment]
> in fact, some users asked me to add this feature because they add the keyring on their bag and want to be informed if the bag is forgotten somewhere. Others let the keyring inside their cars, and it's a good way to get the park location automatically ..

That is a nice idea, like hosek said, but only if I get the notification when the keyring gets out of range and then if I don't accidentally dismiss the notification. It would be a nice idea, instead of just getting a notification to have the last known coordinates kept inside the app.

**Comment by mofosyne** [comment]
Yea a history list of positions would be best

**Comment by sylvek** [comment]
Yes you are wright.

**Comment by sylvek** [comment]
@mofosyne it is ok with my last version ? (https://drive.google.com/file/d/0B2WJ90QJfme5SVMzZ3J6aDNqX2c/view?usp=sharing)

**Comment by mofosyne** [comment]
seems to work. Is there anything different from hosek?

**Comment by sylvek** [comment]
@mofosyne great thks! no only a different way to write the code.
