### ISSUE TITLE
translating to hungarian

### ISSUE THREAD

**Issue by phpmoli** [sylvek/itracing2#60]
Hello Sylvain,

I have a tween relative who keeps loosing her stuff, so i've bought her a chinese itag from aliexpress, just to test out at first, if it is a working solution for her.
I've looked in android market for apps, but all of them requires hundreds of permissions, which is extremely shady from a chinese app-maker. Then found yours, which requires only a few permissions, not chinese and is open source.

So i installed it on her phone, and it is working nice, the problem is she, being a ten-something years old, does not know english yet, only her mother language: hungarian. So i started to look after what can i do, and found out that all texts are in an xml file, i can simply translate.

So i started doing it, and it is still in progress, i just wanted to ask you to check it out and help me in the progress. Please see the current version at [https://github.com/phpmoli/itracing2/blob/master/app/src/main/res/values-hu/strings.xml](https://github.com/phpmoli/itracing2/blob/master/app/src/main/res/values-hu/strings.xml) .

As the hardware was a gift, i dont have it now, so i cannot use the app to see what should i translate, where are the texts in context, so i made a screenshot from every page in the app when i had access to the hardware, and using it now at home. But i still have questions, as a lot of texts was not appearing anywhere, so i dont know the context.
What is the best place to ask you these questions?

**Comment by sylvek** [comment]
Hey!
That's very nice to read your mail. Thank you for you commitment. Please,
feel free to ask your question to an another issue.
I will come back to you soon to integrate your language.

Regards
Sylvain

**Comment by phpmoli** [comment]
Dear Sylvain,

I am almost finished, i have already wrote a couple of questions in form of comments to the xml.

Could you please take a look? Maybe it is the best to answer them here.

**Comment by phpmoli** [comment]
One more thought: should i translate the android market description and make screenshots (after you commited a new release, of course)?

By the way, you should really write a _longer_ english Market description with more keywords, like iTag, anti-theft, beep, ringtone, position, intent, russian, open source, etc. I am happy to translate it after :)

**Comment by sylvek** [comment]
Hey!!
that's sound great if you could take screenshots ! i'm going to generate a new beta version, that you could test.

**Comment by sylvek** [comment]
please check the beta version https://play.google.com/apps/testing/net.sylvek.itracing2

**Comment by phpmoli** [comment]
Dear @sylvek ,

> that's sound great if you could take screenshots !

No :) I mean it is me, who needs the screenshots. To know the context, which the words are in, i need to see where and how the text appears. Translating an app is not just running it through googletranslate, you need to use a few guidelines, like put the most important words in the beginning of the text, so when a user has the largest font size set in android they still know what would be remaining of the text which does not fit on the screen would say (just look at [this](http://cdn.makeuseof.com/wp-content/uploads/2013/06/large_text.jpg) screenshot) or using the same terms consistently throughout the app, so when a user already used a function, they will understand an other unknown function if it contains previously learn terms, like i renamed every use of the immediate alarm on the gadget to the same word of "csipog" which could be translated to "beep" in english.
The comments in the xml needs answers from you.

> i'm going to generate a new beta version, that you could test.

What exactly should i test? I dont have the gadget with me as it was a present to my family relative, and the next time i am going to have it may be 3 months away. If the only thing to test is the language implementation, i can do that without the gadget and with the phone of my girlfriend (as my phone doesnt have hungarian locale).

**Comment by sylvek** [comment]
understood! my bad ... i'm going to send you several screenshots.

**Comment by sylvek** [comment]
[Screenshots.zip](https://github.com/sylvek/itracing2/files/264445/Screenshots.zip)

**Comment by phpmoli** [comment]
Dear @sylvek ,

I've tested the beta release, the translation is working.

I need some further info:

- link_background - is this an intent? where does the text appear?

- link_background_summary - is this an intent? where does the text appear?

- action_connect - needs screenshot. where does the text appear?

- confirm_remove_keyring - needs screenshot. as you see, i rephrased the other confirm dialog text after i had got the screenshot, so it is a valid question :)

- ring_the_device - needs screenshot. where does the text appear?

- actions - needs screenshot. where does the text appear?

- ring_tone_not_found - if it is checking if a file "physically" exists, then why does it say in the english translation to turn up the volume? :)

- confirm_remove_events - needs screenshot

There are some texts in the xml i did not find in the app, these needs confirmation, are they really unused?
link_background , link_background_summary , feedback_summary , action_scan_start , action_connect , confirm_remove_keyring , immediate_alert_summary , ring_the_device , battery_info , rssi_info , actions , confirm_remove_events

**Comment by phpmoli** [comment]
How do i make a pull request to [https://github.com/phpmoli/itracing2/blob/patch-2/app/src/main/res/values-hu/strings.xml](https://github.com/phpmoli/itracing2/blob/patch-2/app/src/main/res/values-hu/strings.xml) ?

**Comment by sylvek** [comment]
done!

**Comment by sylvek** [comment]
i'm going to generate a new beta version.
