### ISSUE TITLE
donate link is geo-restricted

### ISSUE THREAD

**Issue by phpmoli** [sylvek/itracing2#61]
This [https://www.paypal.me/SylvainMaucourt](https://www.paypal.me/SylvainMaucourt) gives me

> Sorry about that... PayPal.Me isn't available in your country.

Maybe use an other link for some specific countries?

**Comment by phpmoli** [comment]
Found additional info: [https://www.paypal.me/pages/countries](https://www.paypal.me/pages/countries)
So either resolve the ip address to the country via a free web service or display both paypalme and an other link to donate so the user can try both.

**Comment by sylvek** [comment]
Hey Moli ..

i take time to answer you .. (i didn't forget your commitment ;)
so .. well .. thank you :D .. i'm going to find a way to win more money ;-)
but before, i'm going to integrate your translation :)

**Comment by JaapHaitsma** [comment]
Having the same issue trying to donate from chile. Solution is just create a donate link with paypal. I have this on a few websites and it works fine
