### ISSUE TITLE
user interface suggestions

### ISSUE THREAD

**Issue by phpmoli** [sylvek/itracing2#62]
Hello Sylvain,

During the translation, i did look a lot at the screenshots i made, and i had thought a lot about the user interface.

I have some suggestions you might consider:
- you should replace the Close X button in the top left corner to a Back arrow image. Close have a meaning of "discard".
- event times should have localization too. I use and love mysql-like times too, but normal people dont get it. e.g in hungarian it should be 2016. május 9. 5:09:01
- put feedback and donate under preferences so the feedback_summary and donate_summary texts could be shown. After that the 3-dot options menu can be replaced to a direct link to preferences then.
- compact data on the event page to help the user to scroll less. 2 rows are not needed, neither of them filling the screen width. Make 1 row with the date first, like: "2016. május 9. 5:09:01 Kapcsolódás"
  Also get rid of the horizontal line separators between the records.
- expand (un-compact) data on the devices page, as users usually have only 1 device anyway, and the checkbox on the right has no explanation at all. Put that checkbox in a new line under the device name, and put the texts link_background and link_background_summary there.
- immediate_alert floating button icon should change to "volume off" material design icon after pressing the button. And then back to the default "volume up" icon when pressing again.
- hide immediate_alert floating button when on tabs device/preferences and history. It covers info here and it is sufficent to be on the dashboard tab.
- something_goes_wrong should be a toast every time there is a bluetooth problem, not only for immediate_alert
- in the dashboard, dont write the battery percentage value on top of the radio signal color circle. It looks like the inner circle color which has the number on it has the same meaning because they are at the same place. I know this has a long java code, you are probably proud for, but it is very confusing. I also know some android versions show the battery state by a circle and this is like that. Either dont show the number, only the graph, or make 2 separate circles, or not even circles but one battery column and a wifi or gsm icon-like signal-meter. I understand this dashboard is a characteristic of the app, but it is confusing.
- event texts should be translated
- maybe ble_not_supported should not be in a toast which disappears after some time, but in a huge popup which has an OK button which closes the app, as without BLE the app cannot do anything.

**Comment by sylvek** [comment]
thank you for your feedback, this is greatly helpful. i'll add your recommandations step by step.

**Comment by phpmoli** [comment]
after seeing your screenshots, some more :)

- at the link_loss_disabled dialog, the dialog title should not be the app name, but the device name

- at the confirm_change_name dialog, there should be a title with the old device name, so when the user wants to rename his device, erases the old name in the input field, then he got distracted by a phone call or the wife and puts down his phone, to come back 3 minutes later, he will not remember which device is he renaming right now, and as he deleted the input field with the old device name, the only way to know which device, is to discard the dialog and start again. Putting the current device name to the dialog title prevents this.

- at the confirm_change_name dialog, the ok, cancel buttons should be right below the input field, as these ok/cancel buttons are not the buttons for the ring and remove buttons. Or as this is a standard android dialog which has the ok/cancel buttons on bottom, put the rename field to the buttom, and put the ring and remove buttons on top.

- at the confirm_change_name dialog, left-align the confirm text

**Comment by phpmoli** [comment]
- at the preferences/double click delay, show the value set under the menu without the need to enter the dialog

**Comment by phpmoli** [comment]
- rename device preferences tab to Actions ?

- redesign preferences tab to somethin like this?
![redes](https://cloud.githubusercontent.com/assets/5528385/15446982/e592f64a-1f30-11e6-9008-54b4dbe9a145.png)

**Comment by sylvek** [comment]
wow molli thanks!
you're very productive! ... (more than me right now)

**Comment by sylvek** [comment]
i have generated a new version containing your translation. I'm not really a good ui designer, and this part asks me a big part of my time (and of course that i don't have)
So you should be patient but i'll do it soon !
