### ISSUE TITLE
iTag (re)connects every 60s

### ISSUE THREAD

**Issue by bmsleight** [sylvek/itracing2#63]
Hi,

The iTag Bleeps every minute.  Hard to explain the beeps, video:-
https://youtu.be/bk3oTYGtULw

Can connect fine, however single and double clicks has not effect.  If I set "On Connect Action" to "capture my position" - I get the event log as follows:-

connected,CAPTURE_POSITION,2016-05-10 22:26:18
connected,CAPTURE_POSITION,2016-05-10 22:26:19
position,51.3982521,-0.1820917,2016-05-10 22:26:19
position,51.3982521,-0.1820917,2016-05-10 22:26:19
connected,CAPTURE_POSITION,2016-05-10 22:27:22
position,51.3982138,-0.1820894,2016-05-10 22:27:22
connected,CAPTURE_POSITION,2016-05-10 22:28:27
position,51.3982459,-0.1821255,2016-05-10 22:28:28

Setting single and double clicks  to "capture my position" and clicking the button does not give an event in the event log and does not capture position. 

Using the "Beta version" had not change. Using foreground mode had not effect. Using new battery has no effect (apart from increase in volume of beeps)

Hardware error ?

Regards,
Brendan

**Comment by sylvek** [comment]
Hi Brendan :)

Thanks you for your video.. this is the first time that i see this problem
:-/
i think that you have a third brand in your hand (not the mle-15 and the
itag from quantic) .. so it should be very interesting you be able to send
some screenshot from this app (after bonded with your itag)
https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=fr
..
an another way should be to capture logs (
https://github.com/sylvek/itracing2/wiki/Contribuate-by-reading-traces)

Regards,
Sylvain

**Comment by bmsleight** [comment]
Sorry for the delay - will get this info later this week.

**Comment by albertferguson** [comment]
I have a similar issue, not the reconnection but where the button click does nothing.
Interestingly when I do the following button clicks work.

- Install Itracing2, pair tag, confirm not working
- Unpair in Itracing.
- Install Itracing, pair. (It has a message about a manufacturer not paying license fees, but everything works)
- Uninstall ITracing
- Pair in Itracing2, button clicks work.

So far I have worked out it continues to respond until I power it off, and then I am back where I started. I am thinking it must send some sort of command to enable the remote before it will do anything. I am only just starting my investigation, so will report back if I work out more.

The bluetooth chip is a BK3431.

**Comment by sylvek** [comment]
Hey! 
Sorry for the delay.... That's seem very strange.
Every work for my without itracing (I never installed it for a while). 
I'll do you test (thank you for you protocol) when I'll back from my vacation.

**Comment by sylvek** [comment]
have you the same issue with the last version?
i saw to options: 
- iTracing2 is going down every x seconds (killed by Android for example…)
- the quality of bluetooth link decreases every x seconds and the phone is loosing the iTag => that's ring (i experiment that everyday with my S6)
