### ISSUE TITLE
more preferences

### ISSUE THREAD

**Issue by Roland768** [sylvek/itracing2#68]
I'm a bit disappointed about configuering the app. I bought the xmarty for my wife, and the distance alarm is complete useless for her, because she is using two bunches of keys and won't change the device every time. She only need the search function, but in both directions, from key to phone (does this exist in itracing2? It won't work for me) and from phone to key. So I expect a fully configurable tool, where I can switch on or off all possibilities. In the original app you can configure phone search and a lot of other things, but also not the distance alarm.

**Comment by Roland768** [comment]
OK you hide the dashboard/preference area very well. I only reached the device list and didn't manage to get on. Then I saw the screenshots on playstore and understand, there must be more, and found it at last. And next time I will leard how to delete stupid posts...

**Comment by sylvek** [comment]
👍
