### ISSUE TITLE
ne fait plus sonner le tel 

### ISSUE THREAD

**Issue by naiiade** [sylvek/itracing2#69]
Bonjour 
Hier l itag faisait sonner mon tel sans problème. 
aujourd'hui ça ne fonctionne plus, jarry desinstallé, re installé. 
Rien n'y fait 
Merci de m'aider

**Comment by sylvek** [comment]
bonjour essayez en sélectionnant l'action sur simple-clic.

**Comment by naiiade** [comment]
C'est bien ce que j'ai fait. Simple clic sonne et double clic arrête. 
J'ai même deselectionné reselectionné, desinstallé... 
Le smartphone fait sonner le porte clef mais plus l'inverse.

**Comment by naiiade** [comment]
C'est bien ce que j'ai fait. Simple clic sonne et double clic arrête. 
J'ai même deselectionné reselectionné, desinstallé... 
Le smartphone fait sonner le porte clef mais plus l'inverse.

**Comment by naiiade** [comment]
C'est bien Ce que j'ai fait. 
J'ai mis Simple clic pour sonne de deux clics Arrête . 
J'ai même deselectionné reselectionné, desinstallé ... 
L application fait sonner le porte clef Mais , plus le smartphone .

Merci 
(bizarre votre site ça traduit du français et français traduit de l'anglais, c'est pas banal le résultat ;-)  )

**Comment by sylvek** [comment]
Bonsoir,

Effectivement c'est étrange. Avez vous des connaissances informatique assez
poussées pour utiliser le SDK Android sur votre ordinateur ?
Cela permettrait de récupérer les traces de l'application et mieux
comprendre le problème.

**Comment by naiiade** [comment]
Non désolée je ne pourrai pas faire ça, merci de m'avoir répondu
