### ISSUE TITLE
Possibility that MLE-15 does not power off when link is lost

### ISSUE THREAD

**Issue by JaapHaitsma** [sylvek/itracing2#70]
Hi Sylvain,

I'd like to use the MLE-15 as a keychain. Such that I can find my phone if I have my keys or vice versa. The thing I notice with the MLE-15 is that it turns off when link is lost. Is there a way to change that behavior. I want the MLE-15 to be always on.

**Comment by sylvek** [comment]
Hello sorry, there is no way :-(
