### ISSUE TITLE
[feature request] - Linux version

### ISSUE THREAD

**Issue by osos** [sylvek/itracing2#72]
I would love to use the iTag devices as a Bluetooth button for home automation or the like. Similar to the [Flic](https://flic.io/) project. 

I have already been able to connect the iTag to a raspberry pi using a bluetooth dongle. But I do not know how to listen for events like button push, hold, double click etc.

Also I do not know how to forward commands from linux to the iTag to engage the buzzer or turn of the alarm to avoid alarm if disconnected.

Please advise where to begin.

**Comment by sylvek** [comment]
Hey welcome :)

bluetooth stuff is focused on
https://github.com/sylvek/itracing2/blob/master/app/src/main/java/net/sylvek/itracing2/BluetoothLEService.java
you have to discover services an check that a service with UDID
0000ffe0-0000-1000-8000-00805f9b34fb
you have to get characteristics of it and set up "notification" feature.
(L. 151)

> "Also I do not know how to forward commands from linux to the iTag to
engage the buzzer or turn of the alarm to avoid alarm if disconnected."
this part is not really configurable.. this feature is hardcoded on the
iTag.. and some devices will beep if the connection is lost, others are
able to make a difference between a connection lost and un bluetooth
connection that could power off voluntarily.

Regards

**Comment by osos** [comment]
Thanks for the pointer. I will revert if any succes.

If anyone already did this, please let us know.
