### ISSUE TITLE
Custom Audio not working

### ISSUE THREAD

**Issue by LockMan007** [sylvek/itracing2#73]
I tried mp3, wav and ogg and although they play in the preview for selecting the audio, when i press the button on the iTag, your app, just plays the "default ringtone". If I select any built-in ringtone (which are .ogg 44100 format) from the ringtone folder on the internal storage of the device, it will play with that ringtone without any problems. It doesn't appear to be file type or length related, so I suspected it is a limitation in the way the app looks for the audio file to play, such as looking in the "ringtone" folder and if it isn't there, it defaults to the default ringtone, but I copied the audio file to that folder and it still won't use it. I tried opening a ringtone in Audacity on PC and copy/pasting the audio from an mp3 into that file and exporting to ogg and it still doesn't work.

Do you know why this doesn't work? All the built in ringtones are obnoxious, I would rather make my own.

**Comment by sylvek** [comment]
someone else reports me the same issue on a "nexus" phone.
the problem is that i need traces to fix this issue (or a nexus ;)

**Comment by sylvek** [comment]
http://android.stackexchange.com/questions/126983/nexus-5x-wont-use-custom-ringtones-notifications
