### ISSUE TITLE
Comment marche la géolocalisation SVP ?

### ISSUE THREAD

**Issue by giroue16** [sylvek/itracing2#74]
Bonjour,
merci pour votre application androïd nettement plus simple que l'application de bas de mon iTag !
Trouver les clés et mon smartphone fonctionne bien, mais j'ai lu que la géolocalisation des clés perdues est possible. Or je ne vois pas très bien sur quelle URL je peux lire le dernier emplacement de l'iTag attaché à mes clés, ni comment je peux paramétrer cela sur l'application ?
Merci de votre aide.
Eve

**Comment by sylvek** [comment]
Bonsoir,

Il est effectivement possible d'associer une action de géolocalisation à l'iTag.
ex.
- je veux connaitre la dernière position de mon iTag (ou de mon téléphone) au moment où la connexion entre les deux appareils s'est interrompu.
- inversement, à la connexion entre les 2 appareils.
- sur un clic du bouton
- etc

pour se faire, vous devez choisir l'action de "capture de position" en fonction de l'événement.
ensuite, une pastille apparaitra dans votre barre de notification qui vous permettra d'afficher Google Maps avec la position correspondante. Vous pourrez aussi retrouver cette position dans la liste des événements associé à votre appareil.

**Comment by giroue16** [comment]
merci :)
