### ISSUE TITLE
How to reset the iTag?

### ISSUE THREAD

**Issue by petiolarid** [sylvek/itracing2#75]
I've managed to screw up a couple of my iTag devices. Writing the wrong data to the wrong handles or some such stupid dabbling!

I cannot now switch them on with a long-press of the button.

Is there some way to 'factory reset' these devices?

**Comment by sylvek** [comment]
hey!
i've never heard that iTag devices are resetable :-!
could you, please, explain what you've done?

**Comment by petiolarid** [comment]
Thanks sylvek,

I have three devices. All bought from Amazon but from two different sources. Interestingly the ‘Local Name’ of the devices are slightly different. My initial purchase has a ‘Local Name’ of ITAG (all capitals) whilst the other two (from a different source) are iTAG. Subtle but interesting.

One of the things I tried to do was to change these names (to make them unique). My write instructions returned without errors but when I read the names again they had not changed.

Of course I’ve tried replacing the battery on each of my devices – to no avail.

Today, my single working iTag has failed me. It was on my keyring for the last couple of days just accompanying me around the country and each time I looked at the iTag the little blue light was blinking. I made no attempt to interact with it during this time. This morning I noticed that the blue light had gone. No amount of button pressing or battery replacing has made it either beep or show a blue light. Also my scanning for LE devices finds nothing.

I’m guessing that the only way to ‘reset’ these devices is to throw them away and buy another!

Maybe I’ll try to momentarily put 3V onto the RST spot on the circuit board and see if that does the trick. I guess I have nothing to lose. But given that I’ve pretty much decided that these devices are at best, unreliable, this would hardly provide a workable solution even if it worked.

Perhaps I will order myself one of the ‘Nut’ devices – a bit more expensive but maybe they will work better for me.

**Comment by sylvek** [comment]
Hi,

If you are only change the name of your device on itracing2.. In fact, it
doesn't synchronized. I store the custom name in a local database on the
app... And I doesn't try to change it on the device. You can change it by a
long click on the device name in the list of devices.. Changing the device
name may be destructive, it is why I do not change it on the device..

**Comment by sylvek** [comment]
I've took time to read you issue, sorry for the delay. 
Hope you have find a way to reset your itag.. I didn't have issue like yours.
