### ISSUE TITLE
autoreconnect

### ISSUE THREAD

**Issue by Analitico** [sylvek/itracing2#77]
Any way to the tag not beeping when in out of range ? And auto reconnecting when in range ?

regards

**Comment by sylvek** [comment]
Hello, if you have an mle15 (the most delivered), there is no way.. This
feature is hard coded by a freaky guy..

**Comment by Analitico** [comment]
is a mle15, ok, thank you. Do you know any similar devices that doesn't have this problem ?

**Comment by sylvek** [comment]
Yes... One,  mine. You can find more here..
https://github.com/sylvek/itracing2/issues/5

**Comment by Analitico** [comment]
thank you
