### ISSUE TITLE
I can not run custom action.

### ISSUE THREAD

**Issue by Irek66** [sylvek/itracing2#78]
I can not run custom action. I write http://4pda.ru/ and nothing happen. 
What command should I write in the line "custom command"?

**Comment by sylvek** [comment]
hi, you could read this:
https://github.com/sylvek/itracing2/blob/master/app/src/main/java/net/sylvek/itracing2/receivers/CustomAction.java

```
if (action.startsWith("http://")) {
            new CallUrl<>(action + "?address=" + address + "&source=" + source).start();
        }
```
so http://4pda.ru/?address=...&source=... should be called.
look on your events history.

**Comment by Irek66** [comment]
Hi. Thank you for reply. But  http://4pda.ru/?address=...&source=... do not call URL.
And what I should write in custom action to call camera and take a photo.

**Comment by sylvek** [comment]
Hi.

as all actions should be performed without UI interactions, the call is done in background.
if http://4pda.ru is own you, you could check if this url is called by reading your logs.
