### ISSUE TITLE
Connect as regular bluetooth device to use as key for Smart Lock

### ISSUE THREAD

**Issue by Rodot** [sylvek/itracing2#79]
Hello, first of all thank you for your app !

I bought a iTag to use it as a key to my phone using Smart Lock ([https://get.google.com/smartlock/](url)). With Google's Smart Lock, you can use any connected bluetooth device as as key, so your phone will be unlocked when it's nearby. The iTag seemed ideal for this. But I can't connect to it directly from the phone's bluetooth menu, I have to go through the application, I'm not sure why.

In short : would it be possible to make the iTag appear as a regular connected Bluetooth device, so we can use it as a Smart Lock key ?

**Comment by sylvek** [comment]
Hey,

First of all thank you.
I have tried what you said. It seems not possible to use the itag as a
smart lock key in same time with itracing2.. I think that is due to the
uncapacity of the itag to manage two connections.. One with Android smart
lock process and another with itracing2.
Have you tried to remove itracing and itracing2 from your phone?
The second point is that mle15 model (of itag) powers off by itself after 3
minutes if no connection with a device is set..
Please try some other options and keep me in touch!

Regards
Sylvain

Le mer. 28 sept. 2016 14:41, Aurélien Rodot <notifications@github.com> a
écrit :

**Comment by Rodot** [comment]
Hello again, thank you for your quick answer.
When I try to connect to the iTAG through the native android bluetooth menu (it shows up with a keyboard logo), it stays on "pairing" for a while, then a popup says "Unable to communicate with iTAG".
I tried removing your have, and restarting the iTAG, it doesn't help.
But I can connect using the app with no problem. Do you have any authentification or anything in your app for it to connect ? It's weird you can't directly connect to the iTAG.

(French guy here too, cocorico !)

**Comment by sylvek** [comment]
OK on va continuer en français alors!
J'avais testé la liaison "smart lock key" lorsque j'avais reçu mon premier
iTag, mais ça marchait pas super bien.
J'avais mis ça sur le dos de l'application iTracing qui parasitait la
connexion.
Avec les appareils de type bluetooth LE la connexion n'est pas forcement
assurée.. et je ne saurais pas dire comment fonctionne la fonctionnalité
"smart lock key" dans ce cas de figure.. utilise-t-il un pairing?
essaie-t-il seulement de détecter la présence de l'appareil bluetooth?
ceci dit, voici quelques éléments de réponses :
- j'arrive à utiliser le smart lock key avec le bluetooth (appairé et
connecté) de ma voiture (qui est un bon vieux bluetooth)
- j'arrive à utiliser le smart lock key avec mon Mi-fit (appairé et
connecté, avec un Bluetooth 4/LE)
- je n'arrive pas à utiliser le smart lock key avec le bracelet Alta
(fitbit) de ma femme…

je testerai avec un itag (quand j'aurais retrouvé une pile!)

Le mer. 28 sept. 2016 à 18:34, Aurélien Rodot <notifications@github.com> a
écrit :

**Comment by Rodot** [comment]
La fonction "smart lock key" fonctionne avec les différentes enceintes bluetooth que j'ai pu tester, et aussi avec des récepteurs audio bluetooth bon marché. Dans tous les cas il faut être connecté au périphérique, sa présence à proximité ne suffit pas.
C'est là qu'est le problème : je ne peux pas me connecter à l'iTag. Du moins pas par l'interface Android, uniquement par l'application iTracing2.

Sur un Galaxy Note 3, Android 5.0 :
![screenshot_2016-09-29-08-27-35](https://cloud.githubusercontent.com/assets/4189146/18943269/ce294c98-861e-11e6-9966-89b38e40523a.jpg)

Tentative de connection, ça dure environ 30 secondes :
![screenshot_2016-09-29-08-27-41](https://cloud.githubusercontent.com/assets/4189146/18943274/d1a5da26-861e-11e6-80ca-af9924bb988d.jpg)

Echec de la connection, l'iTag se met alors à biper :
![screenshot_2016-09-29-08-28-15](https://cloud.githubusercontent.com/assets/4189146/18943275/d4424c10-861e-11e6-9fcb-ff68c5aff51a.jpg)

Pourtant je peux me connecter via l'application sans problème.

Concernant le Bluetooth Low Energy + Smart Lock :
> Bluetooth Low Energy devices can be used for Smart Lock, but they need to be paired at OS level and it seems that the Fitbit uses some kind of pseudo-pairing at app level.

[http://android.stackexchange.com/questions/88088/why-cant-i-use-my-fitbit-for-smart-lock](url)

D'ailleurs, pour l'iTag, est-ce qu'il y a quelque chose de particulier au niveau de l'application pour permettre la connection ?
Il faudrait que l'appli fasse que l'OS reconnaisse l'iTag comme étant connecté, ou bien que l'appli "émule" un périphérique bluetooth (mais je ne sais pas si c'est possible et c'est moyen niveau sécurité).

**Comment by sylvek** [comment]
Non je fais rien de particulier pour la connexion.. Par contre je pense que
l'appareil ne sait pas gérer plusieurs connexion à la fois.. Donc faut
vraiment s'assurer qu'il n'y a pas de parasitage.

Le jeu. 29 sept. 2016 08:36, Aurélien Rodot <notifications@github.com> a
écrit :

**Comment by Rodot** [comment]
Je ne pense pas qu'il y ai de parasitage.
Avec l'application je peux me connecter à chaque fois.
Via android je n'ai jamais réussi à me connecter, même avec l'application désinstallée.
Si jamais tu retrouves un piles, je serai curieux de savoir si tu arrives à te connecter via Android.
Merci pour ton aide, même si c'est plus ou moins lié à l'application :)

**Comment by sylvek** [comment]
Ok j'essaie de te dire ça dans la journée

Le jeu. 29 sept. 2016 08:45, Aurélien Rodot <notifications@github.com> a
écrit :

**Comment by sylvek** [comment]
je viens "enfin" de faire un test (désolé pour le délai)…
et bien de mon côté, après avoir décocher la case dans iTracing2 à côté de mon iTag, je le vois bien apparaître dans la liste des appareils bluetooth au niveau de l'os (ce qui est normal, quand l'appareil est "lié" à iTracing2, il n'émet plus et devient donc indétectable au niveau d'android, une fois la case décochée, il redevient détectable).
par contre, il m'est impossible de l'appareiller avec mon téléphone (android 6). soit l'option n'existe pas au niveau de l'iTag, soit la qualité du signal est trop changeant (pourtant il est juste à côté de mon téléphone), soit j'ai loupé quelque chose.
dans tous les cas, ça l'air compromis pour l'utiliser avec smartlock…
ceci dit j'utilise un mi band, c'est ça marche vraiment très bien, 15€ sur Amazon ;-)

**Comment by Rodot** [comment]
Merci pour le retour, depuis je suis passé sur des écouteurs bluetooth qui me servent aussi de smartlock. Le mi band à l'air pas mal non plus :)
