### ISSUE TITLE
two single press recognized as one double 

### ISSUE THREAD

**Issue by pit001** [sylvek/itracing2#81]
If I press one time (single press) in a fast sequence on two differen iTags, the App shows it as a double click of the last iTag... 

DoubleClick delay in pref is set to 500ms. Logged by URL on Webserver... 

not deeper checked...

Feature request: Woulde be great to be able to configure a name for each iTag  - is't more easy to remember it - in comparism the mac.

**Comment by sylvek** [comment]
funny. you're, i do not check the origin address of the iTag that dispatches the click.
i'll try to fix it on the next release (2.3.8…)

**Comment by LockMan007** [comment]
On my device, I found 3000 to work great for all of my devices. 300 is ultra difficult on my hardware (cant be pressed that fast most of the time), while 3000 is easy and casual and reliable 100℅ of the time.

**Comment by LockMan007** [comment]
Oh, I misunderstood what you said. Well anyway, I wanted to share my double click setting success story.
