### ISSUE TITLE
Build APK.

### ISSUE THREAD

**Issue by AVL4GITHUB** [sylvek/itracing2#88]
Hi!
I am begginer in Android programming.
I use Android Studio 2.2.3.
I can't  build correct apk. My Andriod telefon can't install it.
Help, plz.
[apk.zip](https://github.com/sylvek/itracing2/files/644414/apk.zip)
Thanks!!!

**Comment by sylvek** [comment]
Hi,

Please give me your stack trace..
. /gradlew assembleDebug
Or
gradlew.bat assembleDebug (on Windows)
Must work.

**Comment by sylvek** [comment]
i wrote this page => https://github.com/sylvek/itracing2/wiki/How-to-construct-the-App'.

**Comment by AVL4GITHUB** [comment]
Thanks!
[gradlew.zip](https://github.com/sylvek/itracing2/files/644500/gradlew.zip)

**Comment by AVL4GITHUB** [comment]
I make apk in Android Studio 2.2.3.

**Comment by sylvek** [comment]
Great :=)

**Comment by AVL4GITHUB** [comment]
I try make apk in Android Studio 2.2.3, but my Andriod telefon can't install it.
https://github.com/sylvek/itracing2/files/644414/apk.zip
