### ISSUE TITLE
newbie question (not really an issue!)

### ISSUE THREAD

**Issue by mtrif** [sylvek/itracing2#89]
Hi, 
Could you please indicate where is the "permanent/background link" option I found mentioned in some places? I could only find "foreground mode" checkbox in the preferences... Is it controlling the same matter?
The question is generated by the "only once" behaviour to which my MLE-15 seem to adhere, hence I am trying to play a little and see if I can make any use of it.
(My phone is a Xiaomi, hence running MIUI... if that makes the difference)

**Comment by sylvek** [comment]
Hi,

You just have to uncheck your device to use it "on demand".. In the first
screen.

Regards
Sylvain
