### ISSUE TITLE
Launch custom intents or urls

### ISSUE THREAD

**Issue by mofosyne** [sylvek/itracing2#9]
Allow for button press to activate an android intent, or send data to a url (e.g. timestamp to url, with gps etc...).

----

btw uri intent (not url) is still useful as android supports launching apps based on uri name (e.g. google.com launch google app).

**Comment by sylvek** [comment]
hee.. i'm back.. i could add "quickly" a text box to add a custom intent like.. "android.intent.action.VIEW"… and maybe a custom string after to add optional values .. ex
android.intent.action.VIEW;http://....?tutu=true

but, it is not too "technical"?

**Comment by Arkenklo** [comment]
A custom URI or URL trigger would be very useful for a "quick and dirty" extension of functionality. For an example, it could trigger an external [IFTTT Event](https://ifttt.com/maker) over REST, making this simple app very powerful indeed. There are surely countless other IoT-integrations that are possible with a simple HTTP request or Android URI.

I'd love to see a quick and dirty textbox for custom intents to get the ball rolling. Maybe hide it behind a "Developer options" menu?

**Comment by sylvek** [comment]
:+1:

**Comment by sylvek** [comment]
look the version 1.9
