### ISSUE TITLE
Issue: simple and double clicks aren't working with iTag IT-06 chinese device

### ISSUE THREAD

**Issue by alper061** [sylvek/itracing2#92]
Hi,

With my itag, simple click and double click aren't working. Not register event, not doing anything. The pair, and beep are working.

Device type: iTag IT-06 Bluetooth Alarm Device

Buyed from:
http://eud.dx.com/product/itag-it-06-wireless-bluetooth-v4-0-anti-lost-alarm-device-for-remote-selfie-recording-black-844342777

Thanks

**Comment by sylvek** [comment]
hi, sorry being late.
i've just done a test, without problem.
may you give me more information about your device.. by using a tool app' like: https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=fr
and take some screenshots.

regards.
