### ISSUE TITLE
Option to turn off iTag beep when out of range. 

### ISSUE THREAD

**Issue by zirtiger** [sylvek/itracing2#94]
Is it possible to add an option to turn off the beeping of the iTag when connection is lost?

I do not want to get reminded when I leave the iTag somewhere but I want it to register the position. As it is now it beeps as soon as I get out of range or turn my Bluetooth off which is really annoying sometimes.

**Comment by sylvek** [comment]
as i know, it's impossible without opening your iTag and bypass the buzzer :(

**Comment by rlesac** [comment]
Hi, 
I came to post the same issue. I think it should be possible as other apps are doing just that.
For example, fr.free.julienGley.iTagAlarm, if I turn off BT or move away, the iTag won't start beeping, but it will mark it as lost.

Such a feature would be very much welcome, as it would allow a new use case, such as marking locations.

**Comment by sylvek** [comment]
i don't know how this app' works. but i know after several tests.. with a permanent link between the iTag and the Phone.. is this link is lost (by the distance) the iTag ring by hardcoded feature.
Maybe it is possible to set the bip to OFF.. for example, when you "ring" the iTag .. the app' set a value on the iTag .. and reset it to stop the ring.

**Comment by skaringa** [comment]
Maybe this helps: My tag offers a "Link-Loss-Service" (0x1803). The documentation https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.service.link_loss.xml states: If the current link loss alert level is “No Alert”, no alerting is done on this device.
So writing the value 0 to this service should turn off the alert.

**Comment by sylvek** [comment]
Perfect 👌

**Comment by rlesac** [comment]
I went with the faster route of just desoldering the buzzer :)
skaringa, what model do you have?
I've checked mine and it doesn't offer the link loss service according to nRF inspection of services.

**Comment by skaringa** [comment]
I bought it from the German store "Pearl". The model number is PX1869 but I think this is only Pearl's internal number. nRF Connect reports manufacturer name "BEKEN". 

![screenshot_2017-03-30-14-34-30](https://cloud.githubusercontent.com/assets/2950257/24504425/949b72b8-1556-11e7-9d4e-ca9fb4de907e.png)
![screenshot_2017-03-30-14-34-57](https://cloud.githubusercontent.com/assets/2950257/24504428/976a8970-1556-11e7-9b1a-d6b490329d31.png)

**Comment by sylvek** [comment]
I'll check my own itag to see if I have this option..

**Comment by rlesac** [comment]
I found ZC23400, which is supposed to have the service. It is also available very cheap on Aliexpress. I'm waiting on mine. Looks like a regular iTag from the outside.

**Comment by sylvek** [comment]
see #101

**Comment by rlesac** [comment]
Great news!
I'm still waiting on my iTags with the link loss option.

**Comment by Fglehmann** [comment]
> I bought it from the German store "Pearl". The model number is PX1869 but I think this is only Pearl's internal number. nRF Connect reports manufacturer name "BEKEN".
> 
> ![screenshot_2017-03-30-14-34-30](https://cloud.githubusercontent.com/assets/2950257/24504425/949b72b8-1556-11e7-9d4e-ca9fb4de907e.png)
> ![screenshot_2017-03-30-14-34-57](https://cloud.githubusercontent.com/assets/2950257/24504428/976a8970-1556-11e7-9b1a-d6b490329d31.png)

Hello, do u remember this app name? 

Tks a lot

Flavio

**Comment by skaringa** [comment]
nRF Connect for Mobile 
https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp

**Comment by makefu** [comment]
Hi all, i know this issue is already closed, but can anyone point me towards a link (aliexpress/ebay/whatever) where i can buy such device? i bought a couple of itags already but none of them provided the link loss service

**Comment by yankobogdan** [comment]
@makefu I am interested in such a device as well. Let me know if you found the right one.

**Comment by makefu** [comment]
@yankobogdan in the end i gave up and just fetched some tile tags from ebay. Today i would probably get either apple tags or whatever is currently coming from google. it is quite sad because the sole purpose for me was to find my keys at home ...
