### ISSUE TITLE
MQTT support?

### ISSUE THREAD

**Issue by rlesac** [sylvek/itracing2#98]
It would be a great addition. Probably easy for you as you've already done MQTT work.

**Comment by sylvek** [comment]
Do you have a use case ?
I have to modernize the "custom action".. It could be easy to interact with someone else with it..

**Comment by rlesac** [comment]
Use case? 
Sure!
I connected an ESP8266 to my building doorphone system so I can use it to open the doors. I hooked it up to a MQTT broker, where it's listening to commands.
Next is using the iTag click to trigger the door opening MQTT command.

**Comment by sylvek** [comment]
Nice! I'm looking for to add a script support like Ruby to extend the
usage.

**Comment by rlesac** [comment]
Ruby might be an overkill, as you could also use Tasker for complex tasks. A simple MQTT implementation seems straight forward to me and would cover a lot of use cases. Like the current custom action, but instead publish to a topic.

**Comment by sylvek** [comment]
please have a look of this pull request #100
