### ISSUE TITLE
Add layout to board  table (Itracing2 freeze-out)

### ISSUE THREAD

**Issue by ZahirSoufiane** [sylvek/itracing2#99]
Hi ,, 
i want to add a new slide (activity) to the dashboard (next to History).
what i have done is this :
add LocationFragment in dashboard package
add location.xml to layout package
and
dashboard/DevicePreferencesFragment.js

`private static final int NUM_PAGES = 4;  //3 was the default value`

`mTab.setTabsFromPagerAdapter(pagerAdapter);
        mTab.getTabAt(0).setText(R.string.dashboard);
        mTab.getTabAt(1).setText(R.string.preferences);
        mTab.getTabAt(2).setText(R.string.events_history);
        mTab.getTabAt(3).setText(R.string.location);`

` @Override
        public Fragment getItem(int position)
        {
            switch (position) {
                case 0:
                    return DashboardFragment.instance(address);
                case 1:
                    return DevicePreferencesFragment.instance(address);
                case 2:
                    return EventsHistoryFragment.instance(address);
                /*case 3:
                    return LocationFragment.instance(address);*/
                default:
                    throw new RuntimeException("no fragment for position " + position);
            }
        }`
``
when i install the apk and git in and when i want to slide to history or the new one on the last the apk freeze and close

**Comment by sylvek** [comment]
humm .. can you please, add the stacktrace? your code seems ok.
the issue comes from LocationFragment, i suppose.
